# Helpful Resources
* https://towardsdatascience.com/walkthrough-mapping-basics-with-bokeh-and-geopandas-in-python-43f40aa5b7e9
* https://docs.bokeh.org/en/latest/docs/user_guide/geo.html
* https://docs.bokeh.org/en/latest/docs/user_guide/jupyter.html

In [3]:
# imports
import geopandas as gpd
import pandas as pd
import json
from bokeh.io import show
from bokeh.models import (CDSView, ColorBar, ColumnDataSource,
                          CustomJS, CustomJSFilter, 
                          GeoJSONDataSource, HoverTool,
                          LinearColorMapper, Slider)
from bokeh.layouts import column, row, widgetbox
from bokeh.palettes import brewer
from bokeh.plotting import figure

# Plotting States With Bokeh

In [4]:
# read in states shapefile from US Census Bureau
states_usa = gpd.read_file("bokeh/cb_2018_us_state_20m.shp")
states_usa.head()

,STATEFP,STATENS,AFFGEOID,GEOID,STUSPS,NAME,LSAD,ALAND,AWATER,geometry
0,24,01714934,0400000US24,24,MD,Maryland,00,25151100280,6979966958,"(POLYGON ((-76.04621299999999 38.025533, -76.0..."
1,19,01779785,0400000US19,19,IA,Iowa,00,144661267977,1084180812,"POLYGON ((-96.62187499999999 42.779255, -96.57..."
2,10,01779781,0400000US10,10,DE,Delaware,00,5045925646,1399985648,"POLYGON ((-75.773786 39.7222, -75.753227999999..."
3,39,01085497,0400000US39,39,OH,Ohio,00,105828882568,10268850702,"(POLYGON ((-82.863342 41.693693, -82.825719999..."
4,42,01779798,0400000US42,42,PA,Pennsylvania,00,115884442321,3394589990,"POLYGON ((-80.519891 40.906661, -80.5196437725..."

In [5]:
states_usa.shape

(52, 10)

In [6]:
# try to visualizae Maryland
states_usa.iloc[0]["geometry"]

In [7]:
# read in combined dataset
combined_df = pd.read_csv("https://raw.githubusercontent.com/ehuang13/w210-presidential-election/master/data/combined_jun13.csv")

In [8]:
combined_df.head()

,Unnamed: 0,ID,YEAR_FIPS,YEAR,STATE_FIPS,COUNTY_FIPS,STATE,COUNTY,FIPS,REP_CANDIDATE,...,NA_FEMALE%,NA_MALE%,WA_FEMALE%,WA_MALE%,TOT_FEMALE%,TOT_MALE%,TOT_POP_LESS19%,TOT_POP_20to39%,TOT_POP_40to59%,TOT_POP_Above60%
0,0,0,20121001,2012,1,1,Alabama,Autauga County,1001.0,Mitt Romney,...,0.000310,0.000511,0.402747,0.390054,0.512912,0.487088,0.293056,0.252858,0.282427,0.171659
1,1,1,20121003,2012,1,3,Alabama,Baldwin County,1003.0,Mitt Romney,...,0.000300,0.000399,0.446461,0.429892,0.510581,0.489419,0.253453,0.230183,0.282293,0.234071
2,2,2,20121005,2012,1,5,Alabama,Barbour County,1005.0,Mitt Romney,...,0.000622,0.001061,0.237175,0.271277,0.469301,0.530699,0.242225,0.270801,0.278741,0.208233
3,3,3,20121007,2012,1,7,Alabama,Bibb County,1007.0,Mitt Romney,...,0.000219,0.001137,0.371240,0.394981,0.463799,0.536201,0.248820,0.283097,0.280955,0.187128
4,4,4,20121009,2012,1,9,Alabama,Blount County,1009.0,Mitt Romney,...,0.000436,0.000627,0.487947,0.477838,0.505255,0.494745,0.271033,0.241682,0.276594,0.210691

In [9]:
# merge combined dataset with state shapefile
merged_df = states_usa.merge(combined_df, left_on="NAME", right_on="STATE")
merged_df.head()

,STATEFP,STATENS,AFFGEOID,GEOID,STUSPS,NAME,LSAD,ALAND,AWATER,geometry,...,NA_FEMALE%,NA_MALE%,WA_FEMALE%,WA_MALE%,TOT_FEMALE%,TOT_MALE%,TOT_POP_LESS19%,TOT_POP_20to39%,TOT_POP_40to59%,TOT_POP_Above60%
0,24,01714934,0400000US24,24,MD,Maryland,00,25151100280,6979966958,"(POLYGON ((-76.04621299999999 38.025533, -76.0...",...,0.000240,0.000227,0.452072,0.442707,0.482712,0.517288,0.221927,0.266361,0.270629,0.241083
1,24,01714934,0400000US24,24,MD,Maryland,00,25151100280,6979966958,"(POLYGON ((-76.04621299999999 38.025533, -76.0...",...,0.000575,0.000567,0.389527,0.385798,0.505547,0.494453,0.256948,0.266186,0.300513,0.176353
2,24,01714934,0400000US24,24,MD,Maryland,00,25151100280,6979966958,"(POLYGON ((-76.04621299999999 38.025533, -76.0...",...,0.000317,0.000334,0.342624,0.315590,0.527542,0.472458,0.249249,0.262140,0.284017,0.204594
3,24,01714934,0400000US24,24,MD,Maryland,00,25151100280,6979966958,"(POLYGON ((-76.04621299999999 38.025533, -76.0...",...,0.000382,0.000236,0.412955,0.407089,0.507383,0.492617,0.286005,0.211781,0.337753,0.164460
4,24,01714934,0400000US24,24,MD,Maryland,00,25151100280,6979966958,"(POLYGON ((-76.04621299999999 38.025533, -76.0...",...,0.001089,0.002057,0.420070,0.403794,0.512676,0.487324,0.278090,0.239033,0.291372,0.191505

In [10]:
# drop Alaska and Hawaii
merged_df = merged_df.loc[~merged_df["NAME"].isin(["Alaska", "Hawaii"])]

In [11]:
# input GeoJSON source that contains features for plotting
geosource = GeoJSONDataSource(geojson = merged_df.to_json())

In [ ]:
# plot map

# create figure object.
plot = figure(title = 'Test Bokeh Map', 
           plot_height = 600 ,
           plot_width = 950, 
           toolbar_location = 'below',
           tools = "pan, wheel_zoom, box_zoom, reset")
plot.xgrid.grid_line_color = None
plot.ygrid.grid_line_color = None

# add patch renderer to figure.
states = plot.patches('xs','ys', source = geosource,
                   fill_color = None,
                   line_color = "gray", 
                   line_width = 0.25, 
                   fill_alpha = 1)
# create hover tool
plot.add_tools(HoverTool(renderers = [states],
                      tooltips = [('State','@NAME'),
                                ('Votes','@COUNTY_TOTALVOTES')]))

# generates a map on separate tab in browser
show(plot)

# Plotting Counties With Bokeh

In [12]:
# read in counties shapefile from US Census Bureau
counties_usa = gpd.read_file("bokeh/cb_2018_us_county_20m.shp")
counties_usa.head()

,STATEFP,COUNTYFP,COUNTYNS,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER,geometry
0,37,017,01026336,0500000US37017,37017,Bladen,06,2265887723,33010866,"POLYGON ((-78.90199799999999 34.835268, -78.79..."
1,37,167,01025844,0500000US37167,37167,Stanly,06,1023370459,25242751,"POLYGON ((-80.49737499999999 35.202104, -80.29..."
2,39,153,01074088,0500000US39153,39153,Summit,06,1069181981,18958267,"POLYGON ((-81.68698999999999 41.135956, -81.68..."
3,42,113,01213687,0500000US42113,42113,Sullivan,06,1165338428,6617028,"POLYGON ((-76.81373099999999 41.590034, -76.22..."
4,48,459,01384015,0500000US48459,48459,Upshur,06,1509910100,24878888,"POLYGON ((-95.15273999999999 32.660949, -95.15..."

In [48]:
test = ["Bladen", "Stanly", "Summit", "Sullivan", "Upshur"]
test_county = bokeh_counties[bokeh_counties["County Name"].isin(test)]
test_county.head()

,County Name,State-County,state abbr,State Abbr.,geometry,value,GEO_ID,GEO_ID2,Geographic Name,STATE num,COUNTY num,FIPS formula,Has error
302,Summit,CO-Summit,co,CO,<Polygon><outerBoundaryIs><LinearRing><coordin...,979.097472,05000US08117,8117,"Summit County, Colorado",8,117,8117.0,NaN
772,Sullivan,IN-Sullivan,in,IN,<Polygon><outerBoundaryIs><LinearRing><coordin...,629.961754,05000US18153,18153,"Sullivan County, Indiana",18,153,18153.0,NaN
1586,Sullivan,MO-Sullivan,mo,MO,<Polygon><outerBoundaryIs><LinearRing><coordin...,752.096606,05000US29211,29211,"Sullivan County, Missouri",29,211,29211.0,NaN
1772,Sullivan,NH-Sullivan,nh,NH,<Polygon><outerBoundaryIs><LinearRing><coordin...,880.860953,05000US33019,33019,"Sullivan County, New Hampshire",33,19,33019.0,NaN
1879,Sullivan,NY-Sullivan,ny,NY,<Polygon><outerBoundaryIs><LinearRing><coordin...,332.210472,05000US36105,36105,"Sullivan County, New York",36,105,36105.0,NaN

In [19]:
# read in bokeh counties data to merge combined_df with counties shape file
bokeh_counties = pd.read_csv("bokeh/US_Counties.csv")
bokeh_counties.head()

,County Name,State-County,state abbr,State Abbr.,geometry,value,GEO_ID,GEO_ID2,Geographic Name,STATE num,COUNTY num,FIPS formula,Has error
0,Autauga,AL-Autauga,al,AL,<Polygon><outerBoundaryIs><LinearRing><coordin...,126.404492,05000US01001,1001,"Autauga County, Alabama",1,1,1001.0,NaN
1,Baldwin,AL-Baldwin,al,AL,<Polygon><outerBoundaryIs><LinearRing><coordin...,486.079322,05000US01003,1003,"Baldwin County, Alabama",1,3,1003.0,NaN
2,Barbour,AL-Barbour,al,AL,<Polygon><outerBoundaryIs><LinearRing><coordin...,583.340415,05000US01005,1005,"Barbour County, Alabama",1,5,1005.0,NaN

In [24]:
combined_df.head(3)

,Unnamed: 0,ID,YEAR_FIPS,YEAR,STATE_FIPS,COUNTY_FIPS,STATE,COUNTY,FIPS,REP_CANDIDATE,...,NA_FEMALE%,NA_MALE%,WA_FEMALE%,WA_MALE%,TOT_FEMALE%,TOT_MALE%,TOT_POP_LESS19%,TOT_POP_20to39%,TOT_POP_40to59%,TOT_POP_Above60%
0,0,0,20121001,2012,1,1,Alabama,Autauga County,1001.0,Mitt Romney,...,0.000310,0.000511,0.402747,0.390054,0.512912,0.487088,0.293056,0.252858,0.282427,0.171659
1,1,1,20121003,2012,1,3,Alabama,Baldwin County,1003.0,Mitt Romney,...,0.000300,0.000399,0.446461,0.429892,0.510581,0.489419,0.253453,0.230183,0.282293,0.234071
2,2,2,20121005,2012,1,5,Alabama,Barbour County,1005.0,Mitt Romney,...,0.000622,0.001061,0.237175,0.271277,0.469301,0.530699,0.242225,0.270801,0.278741,0.208233

In [45]:
# merge bokeh_counties with combined_df on FIPS
merged_df2 = combined_df.merge(bokeh_counties, left_on="FIPS", right_on="FIPS formula")
merged_df2.head(3)

,Unnamed: 0,ID,YEAR_FIPS,YEAR,STATE_FIPS,COUNTY_FIPS,STATE,COUNTY,FIPS,REP_CANDIDATE,...,State Abbr.,geometry,value,GEO_ID,GEO_ID2,Geographic Name,STATE num,COUNTY num,FIPS formula,Has error
0,0,0,20121001,2012,1,1,Alabama,Autauga County,1001.0,Mitt Romney,...,AL,<Polygon><outerBoundaryIs><LinearRing><coordin...,126.404492,05000US01001,1001,"Autauga County, Alabama",1,1,1001.0,NaN
1,290,316,20161001,2016,1,1,Alabama,Autauga County,1001.0,Donald Trump,...,AL,<Polygon><outerBoundaryIs><LinearRing><coordin...,126.404492,05000US01001,1001,"Autauga County, Alabama",1,1,1001.0,NaN
2,6231,9429,20001001,2000,1,1,Alabama,Autauga County,1001.0,George W. Bush,...,AL,<Polygon><outerBoundaryIs><LinearRing><coordin...,126.404492,05000US01001,1001,"Autauga County, Alabama",1,1,1001.0,NaN

In [46]:
# merge merged_df2 with counties shapefile on GEOID
merged_df3 = merged_df2.merge(counties_usa, left_on="GEO_ID", right_on="AFFGEOID")
merged_df3.head()

Empty DataFrame
Columns: [Unnamed: 0, ID, YEAR_FIPS, YEAR, STATE_FIPS, COUNTY_FIPS, STATE, COUNTY, FIPS, REP_CANDIDATE, DEM_CANDIDATE, REP_VOTES, DEM_VOTES, COUNTY_TOTALVOTES, WINNING_CANDIDATE, WINNING_PARTY, WINNING_PARTY_BINARY, HOUSE_WINNING_BINARY, SENATE_WINNING_BINARY, UNEMPLOYMENT_RATE, AVG_WAGE_SALARY, AA_FEMALE, AA_MALE, BA_FEMALE, BA_MALE, H_FEMALE, H_MALE, IA_FEMALE, IA_MALE, NA_FEMALE, NA_MALE, TOT_FEMALE, TOT_MALE, TOT_POP, WA_FEMALE, WA_MALE, TOT_POP_LESS19, TOT_MALE_LESS19, TOT_FEMALE_LESS19, TOT_POP_20to39, TOT_MALE_20to39, TOT_FEMALE_20to39, TOT_POP_40to59, TOT_MALE_40to59, TOT_FEMALE_40to59, TOT_POP_Above60, TOT_MALE_Above60, TOT_FEMALE_Above60, AA_FEMALE%, AA_MALE%, BA_FEMALE%, BA_MALE%, H_FEMALE%, H_MALE%, IA_FEMALE%, IA_MALE%, NA_FEMALE%, NA_MALE%, WA_FEMALE%, WA_MALE%, TOT_FEMALE%, TOT_MALE%, TOT_POP_LESS19%, TOT_POP_20to39%, TOT_POP_40to59%, TOT_POP_Above60%, County Name, State-County, state abbr, State Abbr., geometry_x, value, GEO_ID, GEO_ID2, Geographic Name, STATE num, COUNTY num, FIPS formula, Has error, STATEFP, COUNTYFP, COUNTYNS, AFFGEOID, GEOID, NAME, LSAD, ALAND, AWATER, geometry_y]
Index: []

[0 rows x 89 columns]

In [ ]:
# visualize a county

bokeh_counties.head()

In [ ]:
bokeh_counties.shape