In [1]:
# imports
import pandas as pd
import seaborn as sns

In [26]:
# load in Ahana's final merged dataset
total_data = "https://raw.githubusercontent.com/ehuang13/w210-presidential-election/master/data/Totaldata_Jun_11.csv"
merged_df = pd.read_csv(total_data, encoding = "ISO-8859-1" )

In [27]:
# checkout merged_df
print("Shape of full dataset: {}".format(merged_df.shape))
merged_df.sample(10)

Shape of full dataset: (18855, 65)

,Unnamed: 0,ID,AGEGRP,FIPS_x,YEAR,STATE,COUNTY,STNAME,CTYNAME,AA_FEMALE,...,NA_MALE%,WA_FEMALE%,WA_MALE%,TOT_FEMALE%,TOT_MALE%,TOT_POP_LESS19%,TOT_POP_20to39%,TOT_POP_40to59%,TOT_POP_Above60%,Unemployment_Rate
15378,15378,200451710,Total,51710,2004,51,710,Virginia,Norfolk city,3558,...,0.000773,0.227911,0.264015,0.491086,0.508914,0.281483,0.361630,0.225935,0.130952,5.2
16198,16198,200818077,Total,18077,2008,18,77,Indiana,Jefferson County,120,...,0.000156,0.494275,0.468388,0.513503,0.486497,0.265930,0.249689,0.290230,0.194151,6.1
18814,18814,20088061,Total,8061,2008,8,61,Colorado,Kiowa County,0,...,0.000000,0.501418,0.477305,0.512057,0.487943,0.248227,0.178723,0.301418,0.271631,3.7
16316,16316,200819129,Total,19129,2008,19,129,Iowa,Mills County,31,...,0.000262,0.486580,0.493799,0.495767,0.504233,0.279546,0.219765,0.315047,0.185642,3.7
18287,18287,200849007,Total,49007,2008,49,7,Utah,Carbon County,63,...,0.000584,0.484966,0.475041,0.503892,0.496108,0.300185,0.253625,0.261847,0.184344,4.3
11959,11959,200048431,Total,48431,2000,48,431,Texas,Sterling County,0,...,0.000000,0.506102,0.487437,0.508973,0.491027,0.315865,0.234027,0.264178,0.185930,3.3
10048,10048,200019165,Total,19165,2000,19,165,Iowa,Shelby County,23,...,0.000000,0.504976,0.484308,0.511252,0.488748,0.284599,0.204914,0.257502,0.252985,2.3
3078,3078,201247037,Total,47037,2012,47,37,Tennessee,Davidson County,9984,...,0.000591,0.335522,0.324900,0.515986,0.484014,0.247473,0.339089,0.260701,0.152737,6.2
2501,2501,201236083,Total,36083,2012,36,83,New York,Rensselaer County,1671,...,0.000195,0.448849,0.435362,0.506172,0.493828,0.248837,0.261151,0.293835,0.196177,7.7
742,742,20204027,Total,4027,2020,4,27,Arizona,Yuma County,1799,...,0.001320,0.444496,0.467487,0.484717,0.515283,0.281245,0.281599,0.201638,0.235518,NaN

In [10]:
# see all columns in merged dataframe
print(merged_df.columns)

Index(['Unnamed: 0', 'ID', 'AGEGRP', 'FIPS_x', 'YEAR', 'STATE', 'COUNTY',
       'STNAME', 'CTYNAME', 'AA_FEMALE', 'AA_MALE', 'BA_FEMALE', 'BA_MALE',
       'H_FEMALE', 'H_MALE', 'IA_FEMALE', 'IA_MALE', 'NA_FEMALE', 'NA_MALE',
       'SUMLEV', 'TOT_FEMALE', 'TOT_MALE', 'TOT_POP', 'WA_FEMALE', 'WA_MALE',
       'TOT_POP_LESS19', 'TOT_MALE_LESS19', 'TOT_FEMALE_LESS19',
       'TOT_POP_20to39', 'TOT_MALE_20to39', 'TOT_FEMALE_20to39',
       'TOT_POP_40to59', 'TOT_MALE_40to59', 'TOT_FEMALE_40to59',
       'TOT_POP_Above60', 'TOT_MALE_Above60', 'TOT_FEMALE_Above60', 'fips',
       'republican_candidate', 'democrat_candidate', 'republican_votes',
       'democrat_votes', 'county_totalvotes', 'winning candidate',
       'winning party', 'avg_wage_salary', 'AA_FEMALE%', 'AA_MALE%',
       'BA_FEMALE%', 'BA_MALE%', 'H_FEMALE%', 'H_MALE%', 'IA_FEMALE%',
       'IA_MALE%', 'NA_FEMALE%', 'NA_MALE%', 'WA_FEMALE%', 'WA_MALE%',
       'TOT_FEMALE%', 'TOT_MALE%', 'TOT_POP_LESS19%', 'TOT_POP_20to39%',
       'TOT_POP_40to59%', 'TOT_POP_Above60%', 'Unemployment_Rate'],
      dtype='object')

In [11]:
# see how many nulls there are within dataframe
merged_df.isnull().sum()

Unnamed: 0                 0
ID                         0
AGEGRP                     0
FIPS_x                     0
YEAR                       0
STATE                      0
COUNTY                     0
STNAME                     0
CTYNAME                    0
AA_FEMALE                  0
AA_MALE                    0
BA_FEMALE                  0
BA_MALE                    0
H_FEMALE                   0
H_MALE                     0
IA_FEMALE                  0
IA_MALE                    0
NA_FEMALE                132
NA_MALE                    0
SUMLEV                     0
TOT_FEMALE                 0
TOT_MALE                   0
TOT_POP                    0
WA_FEMALE                  0
WA_MALE                    0
TOT_POP_LESS19             0
TOT_MALE_LESS19            0
TOT_FEMALE_LESS19          0
TOT_POP_20to39             0
TOT_MALE_20to39            0
                        ...
TOT_MALE_Above60           0
TOT_FEMALE_Above60         0
fips                    3280
republican_candidate    3280
democrat_candidate      3280
republican_votes        3280
democrat_votes          3280
county_totalvotes       3280
winning candidate       3280
winning party           3280
avg_wage_salary         3280
AA_FEMALE%                 0
AA_MALE%                   0
BA_FEMALE%                 0
BA_MALE%                   0
H_FEMALE%                  0
H_MALE%                    0
IA_FEMALE%                 0
IA_MALE%                   0
NA_FEMALE%               132
NA_MALE%                   0
WA_FEMALE%                 0
WA_MALE%                   0
TOT_FEMALE%                0
TOT_MALE%                  0
TOT_POP_LESS19%            0
TOT_POP_20to39%            0
TOT_POP_40to59%            0
TOT_POP_Above60%           0
Unemployment_Rate       3171
Length: 65, dtype: int64

### One hot encode "winning party" column to binary feature
* republican = 1
* democrat = 0

In [28]:
winning_party_binary = pd.get_dummies(merged_df["winning party"], drop_first = True)
merged_df["winning_party_binary"] = winning_party_binary

In [29]:
merged_df.sample(10)

,Unnamed: 0,ID,AGEGRP,FIPS_x,YEAR,STATE,COUNTY,STNAME,CTYNAME,AA_FEMALE,...,WA_FEMALE%,WA_MALE%,TOT_FEMALE%,TOT_MALE%,TOT_POP_LESS19%,TOT_POP_20to39%,TOT_POP_40to59%,TOT_POP_Above60%,Unemployment_Rate,winning_party_binary
4174,4174,201618039,Total,18039,2016,18,39,Indiana,Elkhart County,1236,...,0.454605,0.444202,0.505346,0.494654,0.304086,0.252358,0.254576,0.188980,3.5,1
8843,8843,202048073,Total,48073,2020,48,73,Texas,Cherokee County,145,...,0.402875,0.409264,0.489998,0.510002,0.284473,0.237793,0.241748,0.235986,NaN,0
3060,3060,201247001,Total,47001,2012,47,1,Tennessee,Anderson County,439,...,0.479635,0.448452,0.516836,0.483164,0.242234,0.223287,0.292950,0.241529,7.9,1
6219,6219,201648477,Total,48477,2016,48,477,Texas,Washington County,328,...,0.398384,0.388821,0.507325,0.492675,0.259505,0.222183,0.252383,0.265928,5.1,1
7472,7472,202023023,Total,23023,2020,23,23,Maine,Sagadahoc County,166,...,0.494191,0.465398,0.514116,0.485884,0.208789,0.217854,0.272549,0.300808,NaN,0
6864,6864,202016059,Total,16059,2020,16,59,Idaho,Lemhi County,23,...,0.473056,0.486245,0.493782,0.506218,0.203241,0.182012,0.218063,0.396684,NaN,0
15164,15164,200449047,Total,49047,2004,49,47,Utah,Uintah County,58,...,0.438726,0.446858,0.499642,0.500358,0.365762,0.257596,0.238997,0.137645,5.1,1
16743,16743,200826041,Total,26041,2008,26,41,Michigan,Delta County,81,...,0.482493,0.470785,0.505508,0.494492,0.241938,0.204449,0.311941,0.241672,8.3,0
17891,17891,200846047,Total,46047,2008,46,47,South Dakota,Fall River County,15,...,0.441903,0.458422,0.491882,0.508118,0.216151,0.156996,0.326839,0.300014,3.4,1
437,437,20165021,Total,5021,2016,5,21,Arkansas,Clay County,11,...,0.498464,0.475976,0.510688,0.489312,0.240766,0.217951,0.266392,0.274891,5.6,1

In [30]:
merged_df[["winning party", "winning_party_binary"]].sample(10)

      winning party  winning_party_binary
16055    republican                     1
16434    republican                     1
16787      democrat                     0
6604            NaN                     0
11445    republican                     1
8283            NaN                     0
3319     republican                     1
8799            NaN                     0
12770    republican                     1
1208     republican                     1

### Explore if we could drop null values
* merged_df before dropping null values has: 18,855 rows and 66 columns
* merged_df after dropping null values has: 15,437 rows and 66 columns

In [40]:
merged_df2 = merged_df.dropna()
merged_df2.shape

(15437, 66)

In [41]:
merged_df2.sample(10)

,Unnamed: 0,ID,AGEGRP,FIPS_x,YEAR,STATE,COUNTY,STNAME,CTYNAME,AA_FEMALE,...,WA_FEMALE%,WA_MALE%,TOT_FEMALE%,TOT_MALE%,TOT_POP_LESS19%,TOT_POP_20to39%,TOT_POP_40to59%,TOT_POP_Above60%,Unemployment_Rate,winning_party_binary
12754,12754,200413097,Total,13097,2004,13,97,Georgia,Douglas County,690,...,0.360713,0.351540,0.513897,0.486103,0.298116,0.300880,0.285483,0.115520,4.8,1
6056,6056,201648151,Total,48151,2016,48,151,Texas,Fisher County,7,...,0.468485,0.457422,0.505017,0.494983,0.236172,0.191922,0.265500,0.306406,4.3,1
3807,3807,201612061,Total,12061,2016,12,61,Florida,Indian River County,992,...,0.454229,0.418470,0.519558,0.480442,0.196333,0.179810,0.247818,0.376039,6.0,1
13563,13563,200424045,Total,24045,2004,24,45,Maryland,Wicomico County,875,...,0.380272,0.348903,0.523518,0.476482,0.277359,0.280083,0.274691,0.167867,4.4,1
1914,1914,201226103,Total,26103,2012,26,103,Michigan,Marquette County,237,...,0.470557,0.469140,0.494842,0.505158,0.229807,0.278422,0.280658,0.211112,8.1,0
11167,11167,200037143,Total,37143,2000,37,143,North Carolina,Perquimans County,13,...,0.365204,0.344270,0.522649,0.477351,0.252001,0.214267,0.279884,0.253848,3.9,1
11528,11528,200042127,Total,42127,2000,42,127,Pennsylvania,Wayne County,88,...,0.489167,0.483945,0.498333,0.501667,0.260345,0.227018,0.285535,0.227102,4.5,1
18019,18019,200847169,Total,47169,2008,47,169,Tennessee,Trousdale County,11,...,0.444112,0.438264,0.506239,0.493761,0.261632,0.244346,0.299194,0.194827,8.4,1
6022,6022,201648083,Total,48083,2016,48,83,Texas,Coleman County,38,...,0.467506,0.465249,0.501366,0.498634,0.240822,0.182963,0.270880,0.305334,5.8,1
17526,17526,200838089,Total,38089,2008,38,89,North Dakota,Stark County,134,...,0.485589,0.476916,0.503840,0.496160,0.256386,0.254099,0.281110,0.208405,2.4,1

### Save one hot encoded dataframe to csv file

In [45]:
# reorder columns
ordered_cols = ['Unnamed: 0', 'ID', 'AGEGRP', 'FIPS_x', 'YEAR', 'STATE', 'COUNTY',
       'STNAME', 'CTYNAME', 'AA_FEMALE', 'AA_MALE', 'BA_FEMALE', 'BA_MALE',
       'H_FEMALE', 'H_MALE', 'IA_FEMALE', 'IA_MALE', 'NA_FEMALE', 'NA_MALE',
       'SUMLEV', 'TOT_FEMALE', 'TOT_MALE', 'TOT_POP', 'WA_FEMALE', 'WA_MALE',
       'TOT_POP_LESS19', 'TOT_MALE_LESS19', 'TOT_FEMALE_LESS19',
       'TOT_POP_20to39', 'TOT_MALE_20to39', 'TOT_FEMALE_20to39',
       'TOT_POP_40to59', 'TOT_MALE_40to59', 'TOT_FEMALE_40to59',
       'TOT_POP_Above60', 'TOT_MALE_Above60', 'TOT_FEMALE_Above60', 'fips',
       'republican_candidate', 'democrat_candidate', 'republican_votes',
       'democrat_votes', 'county_totalvotes', 'winning candidate',
       'winning party', 'winning_party_binary', 'avg_wage_salary', 'AA_FEMALE%', 'AA_MALE%',
       'BA_FEMALE%', 'BA_MALE%', 'H_FEMALE%', 'H_MALE%', 'IA_FEMALE%',
       'IA_MALE%', 'NA_FEMALE%', 'NA_MALE%', 'WA_FEMALE%', 'WA_MALE%',
       'TOT_FEMALE%', 'TOT_MALE%', 'TOT_POP_LESS19%', 'TOT_POP_20to39%',
       'TOT_POP_40to59%', 'TOT_POP_Above60%', 'Unemployment_Rate']

merged_df2 = merged_df2.reindex(columns = ordered_cols)

In [49]:
# output one hot encoded dataframe with null values to csv file
merged_df2.to_csv("totaldata_encoded_jun11.csv")