In [3]:
# imports
import pandas as pd
import seaborn as sns

In [4]:
# load in Ahana's final merged dataset
total_data = "https://raw.githubusercontent.com/ehuang13/w210-presidential-election/master/data/Totaldata_Jun_21.csv"
merged_df = pd.read_csv(total_data, encoding = "ISO-8859-1")

In [5]:
# checkout merged_df
print("Shape of full dataset: {}".format(merged_df.shape))
merged_df.sample(10)

Shape of full dataset: (18855, 64)

,Unnamed: 0,ID,AGEGRP,FIPS_x,YEAR,STATE,COUNTY,STNAME,CTYNAME,AA_FEMALE,...,NA_MALE%,WA_FEMALE%,WA_MALE%,TOT_FEMALE%,TOT_MALE%,TOT_POP_LESS19%,TOT_POP_20to39%,TOT_POP_40to59%,TOT_POP_Above60%,Unemployment_Rate
9715,9715,200013307,Total,13307,2000,13,307,Georgia,Webster County,0,...,0.000000,0.253975,0.269456,0.497490,0.502510,0.281590,0.254393,0.268201,0.195816,3.8
1002,1002,201212101,Total,12101,2012,12,101,Florida,Pasco County,5658,...,0.000451,0.466811,0.441612,0.513899,0.486101,0.233627,0.217313,0.274346,0.274715,9.0
10434,10434,200025023,Total,25023,2000,25,23,Massachusetts,Plymouth County,2510,...,0.000307,0.469839,0.444432,0.512729,0.487271,0.291018,0.265253,0.288173,0.155556,2.7
11377,11377,200040073,Total,40073,2000,40,73,Oklahoma,Kingfisher County,18,...,0.000000,0.475883,0.452053,0.512561,0.487439,0.299742,0.236291,0.265360,0.198608,2.2
17454,17454,200837145,Total,37145,2008,37,145,North Carolina,Person County,59,...,0.000000,0.359349,0.342793,0.517151,0.482849,0.264668,0.227675,0.307585,0.200072,7.2
10940,10940,200031161,Total,31161,2000,31,161,Nebraska,Sheridan County,7,...,0.000000,0.450857,0.436793,0.510346,0.489654,0.279179,0.185742,0.270934,0.264145,2.9
13484,13484,200422061,Total,22061,2004,22,61,Louisiana,Lincoln Parish,285,...,0.000207,0.288339,0.290636,0.513126,0.486874,0.297894,0.338478,0.215186,0.148442,6.5
6556,6556,201655101,Total,55101,2016,55,101,Wisconsin,Racine County,1419,...,0.000308,0.424666,0.416839,0.504848,0.495152,0.261501,0.240047,0.288288,0.210165,4.9
17966,17966,200847063,Total,47063,2008,47,63,Tennessee,Hamblen County,232,...,0.000552,0.475029,0.453500,0.510716,0.489284,0.259076,0.254351,0.277228,0.209345,7.1
16933,16933,200828081,Total,28081,2008,28,81,Mississippi,Lee County,261,...,0.000112,0.369385,0.346582,0.521046,0.478954,0.296756,0.262658,0.270093,0.170492,6.9

In [6]:
# see all columns in merged dataframe
print(merged_df.columns)

Index(['Unnamed: 0', 'ID', 'AGEGRP', 'FIPS_x', 'YEAR', 'STATE', 'COUNTY',
       'STNAME', 'CTYNAME', 'AA_FEMALE', 'AA_MALE', 'BA_FEMALE', 'BA_MALE',
       'H_FEMALE', 'H_MALE', 'IA_FEMALE', 'IA_MALE', 'NA_FEMALE', 'NA_MALE',
       'SUMLEV', 'TOT_FEMALE', 'TOT_MALE', 'TOT_POP', 'WA_FEMALE', 'WA_MALE',
       'TOT_POP_LESS19', 'TOT_MALE_LESS19', 'TOT_FEMALE_LESS19',
       'TOT_POP_20to39', 'TOT_MALE_20to39', 'TOT_FEMALE_20to39',
       'TOT_POP_40to59', 'TOT_MALE_40to59', 'TOT_FEMALE_40to59',
       'TOT_POP_Above60', 'TOT_MALE_Above60', 'TOT_FEMALE_Above60',
       'republican_candidate', 'democrat_candidate', 'republican_votes',
       'democrat_votes', 'county_totalvotes', 'winning candidate',
       'winning party', 'avg_wage_salary', 'AA_FEMALE%', 'AA_MALE%',
       'BA_FEMALE%', 'BA_MALE%', 'H_FEMALE%', 'H_MALE%', 'IA_FEMALE%',
       'IA_MALE%', 'NA_FEMALE%', 'NA_MALE%', 'WA_FEMALE%', 'WA_MALE%',
       'TOT_FEMALE%', 'TOT_MALE%', 'TOT_POP_LESS19%', 'TOT_POP_20to39%',
       'TOT_POP_40to59%', 'TOT_POP_Above60%', 'Unemployment_Rate'],
      dtype='object')

In [7]:
# see how many nulls there are within dataframe
merged_df.isnull().sum()

Unnamed: 0                 0
ID                         0
AGEGRP                     0
FIPS_x                     0
YEAR                       0
STATE                      0
COUNTY                     0
STNAME                     0
CTYNAME                    0
AA_FEMALE                  0
AA_MALE                    0
BA_FEMALE                  0
BA_MALE                    0
H_FEMALE                   0
H_MALE                     0
IA_FEMALE                  0
IA_MALE                    0
NA_FEMALE                  0
NA_MALE                    0
SUMLEV                     0
TOT_FEMALE                 0
TOT_MALE                   0
TOT_POP                    0
WA_FEMALE                  0
WA_MALE                    0
TOT_POP_LESS19             0
TOT_MALE_LESS19            0
TOT_FEMALE_LESS19          0
TOT_POP_20to39             0
TOT_MALE_20to39            0
                        ...
TOT_POP_Above60            0
TOT_MALE_Above60           0
TOT_FEMALE_Above60         0
republican_candidate    3280
democrat_candidate      3280
republican_votes        3280
democrat_votes          3280
county_totalvotes       3280
winning candidate       3280
winning party           3280
avg_wage_salary         3280
AA_FEMALE%                 0
AA_MALE%                   0
BA_FEMALE%                 0
BA_MALE%                   0
H_FEMALE%                  0
H_MALE%                    0
IA_FEMALE%                 0
IA_MALE%                   0
NA_FEMALE%                 0
NA_MALE%                   0
WA_FEMALE%                 0
WA_MALE%                   0
TOT_FEMALE%                0
TOT_MALE%                  0
TOT_POP_LESS19%            0
TOT_POP_20to39%            0
TOT_POP_40to59%            0
TOT_POP_Above60%           0
Unemployment_Rate       3171
Length: 64, dtype: int64

### One hot encode "winning party" column to binary feature
* republican = 1
* democrat = 0

In [8]:
winning_party_binary = pd.get_dummies(merged_df["winning party"], drop_first = True)
merged_df["winning_party_binary"] = winning_party_binary

In [9]:
merged_df.sample(10)

,Unnamed: 0,ID,AGEGRP,FIPS_x,YEAR,STATE,COUNTY,STNAME,CTYNAME,AA_FEMALE,...,WA_FEMALE%,WA_MALE%,TOT_FEMALE%,TOT_MALE%,TOT_POP_LESS19%,TOT_POP_20to39%,TOT_POP_40to59%,TOT_POP_Above60%,Unemployment_Rate,winning_party_binary
873,873,20206111,Total,6111,2020,6,111,California,Ventura County,36235,...,0.423105,0.417894,0.504894,0.495106,0.254674,0.265402,0.261963,0.217961,NaN,0
16016,16016,200816005,Total,16005,2008,16,5,Idaho,Bannock County,538,...,0.466283,0.458633,0.503542,0.496458,0.309032,0.300260,0.242910,0.147798,4.7,1
3703,3703,201255049,Total,55049,2012,55,49,Wisconsin,Iowa County,78,...,0.488879,0.491833,0.498670,0.501330,0.267421,0.217659,0.312624,0.202296,6.7,0
3518,3518,201251139,Total,51139,2012,51,139,Virginia,Page County,55,...,0.490942,0.473573,0.508227,0.491773,0.236475,0.222056,0.296435,0.245034,10.2,1
15823,15823,200812083,Total,12083,2008,12,83,Florida,Marion County,2360,...,0.437190,0.409914,0.517971,0.482029,0.221393,0.199694,0.261908,0.317006,8.1,1
5558,5558,201639115,Total,39115,2016,39,115,Ohio,Morgan County,12,...,0.465943,0.464518,0.500814,0.499186,0.240095,0.213569,0.279647,0.266689,8.3,1
4288,4288,201619083,Total,19083,2016,19,83,Iowa,Hardin County,64,...,0.485200,0.476372,0.498009,0.501991,0.246264,0.212913,0.263112,0.277710,3.9,1
18460,18460,200851159,Total,51159,2008,51,159,Virginia,Richmond County,15,...,0.318799,0.347019,0.434755,0.565245,0.198281,0.267133,0.300764,0.233821,5.0,0
16490,16490,20082105,Total,2105,2008,2,105,Alaska,Hoonah-Angoon Census Area,11,...,0.214541,0.263158,0.464318,0.535682,0.239518,0.201606,0.375558,0.183318,NaN,0
3401,3401,201248493,Total,48493,2012,48,493,Texas,Wilson County,136,...,0.479876,0.476810,0.502473,0.497527,0.288130,0.211835,0.310310,0.189725,5.5,1

In [10]:
merged_df[["winning party", "winning_party_binary"]].sample(10)

      winning party  winning_party_binary
17285      democrat                     0
8471            NaN                     0
4691     republican                     1
6293     republican                     1
15313    republican                     1
223        democrat                     0
14860    republican                     1
6918            NaN                     0
13715    republican                     1
5898     republican                     1

In [11]:
election_years = [2020]

F20_df = merged_df[merged_df["YEAR"].isin(election_years)]
print("2020 data dimensions: {}".format(F20_df.shape))

2020 data dimensions: (3142, 65)

In [97]:
election_years = [2016]

F16_df = merged_df[merged_df["YEAR"].isin(election_years)]
print("2020 data dimensions: {}".format(F16_df.shape))

2020 data dimensions: (3142, 65)

In [12]:
F20_df.sample(10)

,Unnamed: 0,ID,AGEGRP,FIPS_x,YEAR,STATE,COUNTY,STNAME,CTYNAME,AA_FEMALE,...,WA_FEMALE%,WA_MALE%,TOT_FEMALE%,TOT_MALE%,TOT_POP_LESS19%,TOT_POP_20to39%,TOT_POP_40to59%,TOT_POP_Above60%,Unemployment_Rate,winning_party_binary
7971,7971,202031067,Total,31067,2020,31,67,Nebraska,Gage County,69,...,0.483227,0.481506,0.500535,0.499465,0.246080,0.211464,0.258782,0.283674,NaN,0
7723,7723,202028077,Total,28077,2020,28,77,Mississippi,Lawrence County,23,...,0.334564,0.327258,0.514733,0.485267,0.264633,0.229225,0.254597,0.251546,NaN,0
8499,8499,202041015,Total,41015,2020,41,15,Oregon,Curry County,120,...,0.467277,0.453338,0.507868,0.492132,0.158462,0.166616,0.232280,0.442642,NaN,0
7425,7425,202022057,Total,22057,2020,22,57,Louisiana,Lafourche Parish,430,...,0.408317,0.395862,0.509525,0.490475,0.257341,0.267217,0.258350,0.217092,NaN,0
8458,8458,202040087,Total,40087,2020,40,87,Oklahoma,McClain County,142,...,0.432662,0.426160,0.503714,0.496286,0.278504,0.240990,0.262774,0.217732,NaN,0
7911,7911,202030059,Total,30059,2020,30,59,Montana,Meagher County,8,...,0.476420,0.489818,0.494641,0.505359,0.209003,0.170418,0.221329,0.399250,NaN,0
7876,7876,202029221,Total,29221,2020,29,221,Missouri,Washington County,40,...,0.470633,0.481378,0.485306,0.514694,0.249128,0.235737,0.276350,0.238784,NaN,0
7207,7207,202020071,Total,20071,2020,20,71,Kansas,Greeley County,2,...,0.507742,0.468623,0.520782,0.479218,0.282804,0.224124,0.213529,0.279544,NaN,0
689,689,20201115,Total,1115,2020,1,115,Alabama,St. Clair County,428,...,0.444300,0.433352,0.503586,0.496414,0.246713,0.249025,0.272996,0.231266,NaN,0
8766,8766,202047109,Total,47109,2020,47,109,Tennessee,McNairy County,51,...,0.466282,0.448242,0.508671,0.491329,0.238619,0.220308,0.264827,0.276247,NaN,0

### Explore if we could drop null values
* merged_df before dropping null values has: 18,855 rows and 66 columns
* merged_df after dropping null values has: 15,437 rows and 66 columns

In [13]:
merged_df2 = merged_df.dropna()
merged_df2.shape

(15569, 65)

In [15]:
merged_df2.sample(20)

,Unnamed: 0,ID,AGEGRP,FIPS_x,YEAR,STATE,COUNTY,STNAME,CTYNAME,AA_FEMALE,...,WA_FEMALE%,WA_MALE%,TOT_FEMALE%,TOT_MALE%,TOT_POP_LESS19%,TOT_POP_20to39%,TOT_POP_40to59%,TOT_POP_Above60%,Unemployment_Rate,winning_party_binary
4114,4114,201617123,Total,17123,2016,17,123,Illinois,Marshall County,31,...,0.493101,0.484154,0.504557,0.495443,0.221590,0.210971,0.273351,0.294088,6.6,1
14839,14839,200447095,Total,47095,2004,47,95,Tennessee,Lake County,7,...,0.296246,0.381775,0.377051,0.622949,0.197166,0.361636,0.266658,0.174540,6.7,1
18009,18009,200847149,Total,47149,2008,47,149,Tennessee,Rutherford County,3698,...,0.415605,0.412727,0.504876,0.495124,0.297479,0.329174,0.257427,0.115920,5.8,1
15613,15613,20046063,Total,6063,2004,6,63,California,Plumas County,78,...,0.465620,0.469342,0.498115,0.501885,0.240063,0.175311,0.338073,0.246552,9.8,1
4502,4502,201621103,Total,21103,2016,21,103,Kentucky,Henry County,26,...,0.484700,0.464451,0.508807,0.491193,0.260543,0.222615,0.288892,0.227951,4.1,1
6345,6345,201651141,Total,51141,2016,51,141,Virginia,Patrick County,35,...,0.470786,0.453785,0.507702,0.492298,0.201529,0.184089,0.297755,0.316626,4.9,1
1365,1365,201218073,Total,18073,2012,18,73,Indiana,Jasper County,81,...,0.491701,0.485909,0.502179,0.497821,0.287825,0.237909,0.275884,0.198382,8.1,1
5948,5948,201647125,Total,47125,2016,47,125,Tennessee,Montgomery County,2655,...,0.360317,0.365424,0.500736,0.499264,0.296390,0.354374,0.225715,0.123521,5.1,1
13607,13607,200426055,Total,26055,2004,26,55,Michigan,Grand Traverse County,256,...,0.493789,0.470544,0.509717,0.490283,0.267879,0.248959,0.305439,0.177723,6.5,1
11637,11637,200046111,Total,46111,2000,46,111,South Dakota,Sanborn County,10,...,0.475336,0.514574,0.483184,0.516816,0.289238,0.201794,0.268311,0.240658,2.4,1
10232,10232,200021103,Total,21103,2000,21,103,Kentucky,Henry County,33,...,0.478947,0.474617,0.501865,0.498135,0.278481,0.266556,0.284277,0.170686,3.2,1
11371,11371,200040063,Total,40063,2000,40,63,Oklahoma,Hughes County,15,...,0.364240,0.374346,0.485866,0.514134,0.255477,0.255760,0.256961,0.231802,5.1,0
11570,11570,200045067,Total,45067,2000,45,67,South Carolina,Marion County,57,...,0.217393,0.207752,0.537984,0.462016,0.305652,0.259197,0.273037,0.162114,9.6,0
18684,18684,200855107,Total,55107,2008,55,107,Wisconsin,Rusk County,27,...,0.488381,0.491135,0.498052,0.501948,0.255742,0.187710,0.303291,0.253257,7.0,0
12543,12543,20008091,Total,8091,2000,8,91,Colorado,Ouray County,6,...,0.480384,0.491593,0.494796,0.505204,0.243662,0.193755,0.379237,0.183347,2.6,1
2574,2574,201237105,Total,37105,2012,37,105,North Carolina,Lee County,342,...,0.382666,0.373717,0.511402,0.488598,0.280500,0.254535,0.270912,0.194054,11.4,1
10212,10212,200021065,Total,21065,2000,21,65,Kentucky,Estill County,3,...,0.512112,0.480183,0.515965,0.484035,0.268168,0.285015,0.264055,0.182762,4.8,1
12572,12572,20041001,Total,1001,2004,1,1,Alabama,Autauga County,186,...,0.410406,0.395491,0.513675,0.486325,0.309231,0.261816,0.276346,0.152607,4.8,1
17576,17576,200839083,Total,39083,2008,39,83,Ohio,Knox County,173,...,0.498788,0.475010,0.512224,0.487776,0.285898,0.245944,0.276323,0.191835,6.4,1
1992,1992,201227093,Total,27093,2012,27,93,Minnesota,Meeker County,37,...,0.485490,0.499293,0.492134,0.507866,0.274722,0.209525,0.291268,0.224485,6.6,1

### Load and merge senate and house election datasets

In [16]:
# load senate and house datasets
senate = "https://raw.githubusercontent.com/ehuang13/w210-presidential-election/master/data/senate.csv"
house = "https://raw.githubusercontent.com/ehuang13/w210-presidential-election/master/data/house.csv"

senate_df = pd.read_csv(senate, encoding = "ISO-8859-1")
house_df = pd.read_csv(house, encoding = "ISO-8859-1")

### Clean up senate election data

In [17]:
# check out senate election dataset
print("Senate data dimensions: {}".format(senate_df.shape))
senate_df.sample(5)

Senate data dimensions: (3421, 18)

,year,state,state_po,state_fips,state_cen,state_ic,office,district,stage,special,candidate,party,writein,mode,candidatevotes,totalvotes,unofficial,version
2598,2010,Nevada,NV,32,88,65,US Senate,statewide,gen,False,Wil Stand,independent,False,total,2119,721404,False,20171011.0
501,1982,Texas,TX,48,74,49,US Senate,statewide,gen,False,NaN,NaN,True,total,127,3103167,False,20171011.0
1325,1996,Alabama,AL,1,63,41,US Senate,statewide,gen,False,Roger Bedford,democrat,False,total,681651,1499393,False,20171011.0
2547,2010,Iowa,IA,19,42,31,US Senate,statewide,gen,False,NaN,NaN,True,total,872,1116063,False,20171011.0
1766,2000,Pennsylvania,PA,42,23,14,US Senate,statewide,gen,False,Rick Santorum,republican,False,total,2481962,4735116,False,20171011.0

In [18]:
# keep only election years data for senate and house elections
election_years = [1998, 2002, 2006, 2010, 2014, 2018]

senate_df = senate_df[senate_df["year"].isin(election_years)]
print("Senate data dimensions: {}".format(senate_df.shape))

Senate data dimensions: (1038, 18)

In [19]:
senate_df.sample(10)

,year,state,state_po,state_fips,state_cen,state_ic,office,district,stage,special,candidate,party,writein,mode,candidatevotes,totalvotes,unofficial,version
1902,2002,New Hampshire,NH,33,12,4,US Senate,statewide,gen,False,Ken Blevens,libertarian,False,total,9835,447135,False,20171011.0
2590,2010,Nevada,NV,32,88,65,US Senate,statewide,gen,False,Jesse Holland,independent,False,total,3175,721404,False,20171011.0
2880,2014,Colorado,CO,8,84,62,US Senate,statewide,gen,False,Mark Udall,democrat,False,total,944203,2041058,False,20171011.0
3384,2018,Tennessee,TN,47,62,54,US Senate,statewide,gen,False,Kevin Lee McCants,independent,False,total,1927,2243740,False,20190110.0
2602,2010,New Hampshire,NH,33,12,4,US Senate,statewide,gen,False,Chris Booth,independent,False,total,9194,454710,False,20171011.0
3274,2018,California,CA,6,93,71,US Senate,statewide,gen,False,Kevin De Leon,democrat,False,total,5093942,11113364,False,20190110.0
3379,2018,Tennessee,TN,47,62,54,US Senate,statewide,gen,False,Marsha Blackburn,republican,False,total,1227483,2243740,False,20190110.0
1603,1998,Pennsylvania,PA,42,23,14,US Senate,statewide,gen,False,Arlen Specter,republican,False,total,1814180,2957499,False,20171011.0
3417,2018,Wyoming,WY,56,83,68,US Senate,statewide,gen,False,John Barrasso,republican,False,total,136210,203420,False,20190110.0
1882,2002,Minnesota,MN,27,41,33,US Senate,statewide,gen,False,NaN,NaN,True,total,1790,2254639,False,20171011.0

In [20]:
# for each senate election in the state, find the winning party

# group each election by year, state, and party
senate_modified = senate_df.groupby(["year", "state", "state_fips", "party"])["party", "candidatevotes"].max().reset_index()

# sort candidate votes by descending to find the candidates with the most votes
senate_modified = senate_modified.sort_values(by=["year", "state", "state_fips", "candidatevotes"], ascending=False)

# get the party with the most votes by election year and state
senate_modified = senate_modified.groupby(["year", "state", "state_fips"]).first().reset_index()

In [21]:
# check out modified senate dataset
senate_modified.head(5)

   year       state  state_fips       party  candidatevotes
0  1998     Alabama           1  republican          817973
1  1998      Alaska           2  republican          165227
2  1998     Arizona           4  republican          696577
3  1998    Arkansas           5    democrat          385878
4  1998  California           6    democrat         4410056

In [22]:
# need to recode winning party to republican or democrat
senate_modified["party"].unique()

array(['republican', 'democrat', 'connecticut for lieberman',
       'democratic-farmer-labor', 'independent'], dtype=object)

In [26]:
# code other democratic affiliated parties to democrat
senate_modified = senate_modified.replace(["democrat (not identified on ballot)", "democratic-farmer-labor", 
                                            "democratic-nonpartisan league"], "democrat")

# code indepdent affiliated parties to independent
senate_modified = senate_modified.replace("independent for Maine", "independent")
senate_modified = senate_modified.replace("connecticut for lieberman", "independent")

# filter out independent party elections
senate_modified = senate_modified[senate_modified.party != "independent"]

In [27]:
# verify only republican and democrat winning elections remain
senate_modified["party"].unique()

array(['republican', 'democrat'], dtype=object)

In [28]:
# create one hot encoded column for winning party
senate_binary = pd.get_dummies(senate_modified["party"], drop_first = True)
senate_modified["senate_winning_party"] = senate_binary

In [30]:
print("Modified senate dataset dimensions: {}".format(senate_modified.shape))
senate_modified.head(5)

Modified senate dataset dimensions: (200, 6)

,year,state,state_fips,party,candidatevotes,senate_winning_party
0,1998,Alabama,1,republican,817973,1
1,1998,Alaska,2,republican,165227,1
2,1998,Arizona,4,republican,696577,1
3,1998,Arkansas,5,democrat,385878,0
4,1998,California,6,democrat,4410056,0

In [31]:
# see how many nulls there are within dataframe
senate_modified.isnull().sum()

year                    0
state                   0
state_fips              0
party                   0
candidatevotes          0
senate_winning_party    0
dtype: int64

In [32]:
#This shows how many states had senate elections
senate_modified['year'].value_counts()

2010    36
2014    34
2002    34
1998    34
2018    31
2006    31
Name: year, dtype: int64

### Clean up house election data

In [33]:
# checkout house election dataset
print("House data dimensions: {}".format(house_df.shape))
house_df.head(10)

House data dimensions: (29636, 19)

,year,state,state_po,state_fips,state_cen,state_ic,office,district,stage,runoff,special,candidate,party,writein,mode,candidatevotes,totalvotes,unofficial,version
0,1976,Alabama,AL,1,63,41,US House,1,gen,False,False,Bill Davenport,democrat,False,total,58906,157170,False,20200424
1,1976,Alabama,AL,1,63,41,US House,1,gen,False,False,Jack Edwards,republican,False,total,98257,157170,False,20200424
2,1976,Alabama,AL,1,63,41,US House,1,gen,False,False,NaN,NaN,True,total,7,157170,False,20200424
3,1976,Alabama,AL,1,63,41,US House,2,gen,False,False,J. Carole Keahey,democrat,False,total,66288,156362,False,20200424
4,1976,Alabama,AL,1,63,41,US House,2,gen,False,False,NaN,NaN,True,total,5,156362,False,20200424
5,1976,Alabama,AL,1,63,41,US House,2,gen,False,False,"William L. """"Bill"""" Dickinson",republican,False,total,90069,156362,False,20200424
6,1976,Alabama,AL,1,63,41,US House,3,gen,False,False,Bill Nichols,democrat,False,total,106935,108048,False,20200424
7,1976,Alabama,AL,1,63,41,US House,3,gen,False,False,NaN,NaN,True,total,2,108048,False,20200424
8,1976,Alabama,AL,1,63,41,US House,3,gen,False,False,Ogburn Gardner,prohibition,False,total,1111,108048,False,20200424
9,1976,Alabama,AL,1,63,41,US House,4,gen,False,False,Tom Bevill,democrat,False,total,141490,176022,False,20200424

In [34]:
# filter for only election years data for senate and house elections
house_df = house_df[house_df["year"].isin(election_years)]
print("House data dimensions: {}".format(house_df.shape))

House data dimensions: (8396, 19)

In [35]:
# house election dataset seems to be structured similarly to senate election dataset
house_modified = house_df.groupby(["year", "state", "state_fips", "party"])["party", "candidatevotes"].max().reset_index()

# sort candidate votes by descending to find the candidates with the most votes
house_modified = house_modified.sort_values(by=["year", "state", "state_fips", "candidatevotes"], ascending=False)

# get the party with the most votes by election year and state
house_modified = house_modified.groupby(["year", "state", "state_fips"]).first().reset_index()

In [36]:
house_modified.head(5)

   year       state  state_fips       party  candidatevotes
0  1998     Alabama           1  republican          154761
1  1998      Alaska           2  republican          139676
2  1998     Arizona           4  republican          137618
3  1998    Arkansas           5  republican          154780
4  1998  California           6    democrat          158446

In [37]:
# need to recode winning party to republican or democrat
house_modified["party"].unique()

array(['republican', 'democrat', 'independent', 'democratic-farmer-labor'], dtype=object)

In [38]:
# code other democratic affiliated parties to democrat
house_modified = house_modified.replace("democratic-farmer-labor", "democrat")

# filter out independent party elections
house_modified = house_modified[house_modified.party != "independent"]

In [39]:
# verify only republican and democrat winning elections remain
house_modified["party"].unique()

array(['republican', 'democrat'], dtype=object)

In [40]:
# create one hot encoded column for winning party
house_binary = pd.get_dummies(house_modified["party"], drop_first = True)
house_modified["house_winning_party"] = house_binary

In [41]:
print("Modified house dataset dimensions: {}".format(house_modified.shape))
house_modified.head(10)

Modified house dataset dimensions: (298, 6)

,year,state,state_fips,party,candidatevotes,house_winning_party
0,1998,Alabama,1,republican,154761,1
1,1998,Alaska,2,republican,139676,1
2,1998,Arizona,4,republican,137618,1
3,1998,Arkansas,5,republican,154780,1
4,1998,California,6,democrat,158446,0
5,1998,Colorado,8,republican,156501,1
6,1998,Connecticut,9,democrat,109726,0
7,1998,Delaware,10,republican,119811,1
8,1998,Florida,12,republican,140525,1
9,1998,Georgia,13,republican,164966,1

In [42]:
# see how many nulls there are within dataframe
house_modified.isnull().sum()

year                   0
state                  0
state_fips             0
party                  0
candidatevotes         0
house_winning_party    0
dtype: int64

In [43]:
#This shows how many states had senate elections
house_modified['year'].value_counts()

2018    50
2014    50
2010    50
2006    50
2002    49
1998    49
Name: year, dtype: int64

### Merge senate and house election dataset

In [44]:
# sort candidate votes by descending to find the candidates with the most votes by district
house_senate_merged = pd.merge(house_modified[["year", "state", "state_fips", "house_winning_party"]],
                               senate_modified[["year", "state", "state_fips", "senate_winning_party"]],
                               how="left", left_on=["year", "state_fips"], right_on=["year", "state_fips"])

In [45]:
house_senate_merged.head()

,year,state_x,state_fips,house_winning_party,state_y,senate_winning_party
0,1998,Alabama,1,1,Alabama,1.0
1,1998,Alaska,2,1,Alaska,1.0
2,1998,Arizona,4,1,Arizona,1.0
3,1998,Arkansas,5,1,Arkansas,0.0
4,1998,California,6,0,California,0.0

In [46]:
# verify data types
house_senate_merged.dtypes

year                      int64
state_x                  object
state_fips                int64
house_winning_party       uint8
state_y                  object
senate_winning_party    float64
dtype: object

In [47]:
# see how many nulls there are within dataframe
house_senate_merged.isnull().sum()

year                     0
state_x                  0
state_fips               0
house_winning_party      0
state_y                 99
senate_winning_party    99
dtype: int64

In [48]:
house_senate_merged["senate_winning_party"].fillna(-1, inplace = True)
house_senate_merged["house_winning_party"].fillna(-1, inplace = True)

In [49]:
# see how many nulls there are within dataframe
house_senate_merged.isnull().sum()

year                     0
state_x                  0
state_fips               0
house_winning_party      0
state_y                 99
senate_winning_party     0
dtype: int64

In [52]:
#replace values to the election years to enable the merge
replace_values = { 1998 : 2000, 2002 : 2004, 2006 : 2008 , 2010 : 2012, 2014 : 2016, 2018 : 2020 }     
house_senate_merged = house_senate_merged.replace({"year": replace_values})  
house_senate_merged.sample(10)

,year,state_x,state_fips,house_winning_party,state_y,senate_winning_party
134,2008,Oregon,41,0,NaN,-1.0
277,2020,New Jersey,34,0,New Jersey,0.0
117,2008,Maryland,24,1,Maryland,0.0
170,2012,Minnesota,27,1,NaN,-1.0
69,2004,Massachusetts,25,0,Massachusetts,0.0
82,2004,North Dakota,38,0,NaN,-1.0
135,2008,Pennsylvania,42,0,Pennsylvania,0.0
169,2012,Michigan,26,1,NaN,-1.0
65,2004,Kentucky,21,1,Kentucky,1.0
89,2004,South Dakota,46,1,South Dakota,0.0

In [53]:
election_years = [2020]

F20_house_senate = house_senate_merged[house_senate_merged["year"].isin(election_years)]
print("2020 data dimensions: {}".format(F20_house_senate.shape))

2020 data dimensions: (50, 6)

In [54]:
election_years = [2000, 2004, 2008, 2012, 2016]

house_senate_merged = house_senate_merged[house_senate_merged["year"].isin(election_years)]
print("senate house data dimensions: {}".format(house_senate_merged.shape))

senate house data dimensions: (248, 6)

### Merge senate and house election dataset to Ahana's total dataset

In [55]:
# verify dataset dimensions before merge
print("Ahana's dataset dimensions: {}".format(merged_df2.shape))

Ahana's dataset dimensions: (15569, 65)

In [56]:
# merge dataframes on election year and state fips code
combined_df = pd.merge(merged_df2, house_senate_merged, how="left", 
                       left_on=["YEAR", "STATE"], right_on=["year", "state_fips"])

In [57]:
print("Combined dataset dimensions: {}".format(combined_df.shape))
combined_df.head()

Combined dataset dimensions: (15569, 71)

,Unnamed: 0,ID,AGEGRP,FIPS_x,YEAR,STATE,COUNTY,STNAME,CTYNAME,AA_FEMALE,...,TOT_POP_40to59%,TOT_POP_Above60%,Unemployment_Rate,winning_party_binary,year,state_x,state_fips,house_winning_party,state_y,senate_winning_party
0,0,20121001,Total,1001,2012,1,1,Alabama,Autauga County,296,...,0.282427,0.171659,6.9,1,2012.0,Alabama,1.0,1.0,Alabama,1.0
1,1,20121003,Total,1003,2012,1,3,Alabama,Baldwin County,833,...,0.282293,0.234071,7.5,1,2012.0,Alabama,1.0,1.0,Alabama,1.0
2,2,20121005,Total,1005,2012,1,5,Alabama,Barbour County,59,...,0.278741,0.208233,11.5,0,2012.0,Alabama,1.0,1.0,Alabama,1.0
3,3,20121007,Total,1007,2012,1,7,Alabama,Bibb County,10,...,0.280955,0.187128,8.5,1,2012.0,Alabama,1.0,1.0,Alabama,1.0
4,4,20121009,Total,1009,2012,1,9,Alabama,Blount County,82,...,0.276594,0.210691,6.9,1,2012.0,Alabama,1.0,1.0,Alabama,1.0

In [58]:
combined_df.columns

Index(['Unnamed: 0', 'ID', 'AGEGRP', 'FIPS_x', 'YEAR', 'STATE', 'COUNTY',
       'STNAME', 'CTYNAME', 'AA_FEMALE', 'AA_MALE', 'BA_FEMALE', 'BA_MALE',
       'H_FEMALE', 'H_MALE', 'IA_FEMALE', 'IA_MALE', 'NA_FEMALE', 'NA_MALE',
       'SUMLEV', 'TOT_FEMALE', 'TOT_MALE', 'TOT_POP', 'WA_FEMALE', 'WA_MALE',
       'TOT_POP_LESS19', 'TOT_MALE_LESS19', 'TOT_FEMALE_LESS19',
       'TOT_POP_20to39', 'TOT_MALE_20to39', 'TOT_FEMALE_20to39',
       'TOT_POP_40to59', 'TOT_MALE_40to59', 'TOT_FEMALE_40to59',
       'TOT_POP_Above60', 'TOT_MALE_Above60', 'TOT_FEMALE_Above60',
       'republican_candidate', 'democrat_candidate', 'republican_votes',
       'democrat_votes', 'county_totalvotes', 'winning candidate',
       'winning party', 'avg_wage_salary', 'AA_FEMALE%', 'AA_MALE%',
       'BA_FEMALE%', 'BA_MALE%', 'H_FEMALE%', 'H_MALE%', 'IA_FEMALE%',
       'IA_MALE%', 'NA_FEMALE%', 'NA_MALE%', 'WA_FEMALE%', 'WA_MALE%',
       'TOT_FEMALE%', 'TOT_MALE%', 'TOT_POP_LESS19%', 'TOT_POP_20to39%',
       'TOT_POP_40to59%', 'TOT_POP_Above60%', 'Unemployment_Rate',
       'winning_party_binary', 'year', 'state_x', 'state_fips',
       'house_winning_party', 'state_y', 'senate_winning_party'],
      dtype='object')

In [59]:
# drop unnecessary columns
dropCombinedCols = ["SUMLEV", "AGEGRP", "FIPS_x", "year", "state_x", "state_fips", "state_y"]
combined_df = combined_df.drop(dropCombinedCols,axis=1)

In [60]:
combined_df.columns

Index(['Unnamed: 0', 'ID', 'YEAR', 'STATE', 'COUNTY', 'STNAME', 'CTYNAME',
       'AA_FEMALE', 'AA_MALE', 'BA_FEMALE', 'BA_MALE', 'H_FEMALE', 'H_MALE',
       'IA_FEMALE', 'IA_MALE', 'NA_FEMALE', 'NA_MALE', 'TOT_FEMALE',
       'TOT_MALE', 'TOT_POP', 'WA_FEMALE', 'WA_MALE', 'TOT_POP_LESS19',
       'TOT_MALE_LESS19', 'TOT_FEMALE_LESS19', 'TOT_POP_20to39',
       'TOT_MALE_20to39', 'TOT_FEMALE_20to39', 'TOT_POP_40to59',
       'TOT_MALE_40to59', 'TOT_FEMALE_40to59', 'TOT_POP_Above60',
       'TOT_MALE_Above60', 'TOT_FEMALE_Above60', 'republican_candidate',
       'democrat_candidate', 'republican_votes', 'democrat_votes',
       'county_totalvotes', 'winning candidate', 'winning party',
       'avg_wage_salary', 'AA_FEMALE%', 'AA_MALE%', 'BA_FEMALE%', 'BA_MALE%',
       'H_FEMALE%', 'H_MALE%', 'IA_FEMALE%', 'IA_MALE%', 'NA_FEMALE%',
       'NA_MALE%', 'WA_FEMALE%', 'WA_MALE%', 'TOT_FEMALE%', 'TOT_MALE%',
       'TOT_POP_LESS19%', 'TOT_POP_20to39%', 'TOT_POP_40to59%',
       'TOT_POP_Above60%', 'Unemployment_Rate', 'winning_party_binary',
       'house_winning_party', 'senate_winning_party'],
      dtype='object')

In [61]:
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 15569 entries, 0 to 15568
Data columns (total 64 columns):
Unnamed: 0              15569 non-null int64
ID                      15569 non-null int64
YEAR                    15569 non-null int64
STATE                   15569 non-null int64
COUNTY                  15569 non-null int64
STNAME                  15569 non-null object
CTYNAME                 15569 non-null object
AA_FEMALE               15569 non-null int64
AA_MALE                 15569 non-null int64
BA_FEMALE               15569 non-null int64
BA_MALE                 15569 non-null int64
H_FEMALE                15569 non-null int64
H_MALE                  15569 non-null int64
IA_FEMALE               15569 non-null int64
IA_MALE                 15569 non-null int64
NA_FEMALE               15569 non-null int64
NA_MALE                 15569 non-null int64
TOT_FEMALE              15569 non-null int64
TOT_MALE                15569 non-null int64
TOT_POP                 15569 non-null int64
WA_FEMALE               15569 non-null int64
WA_MALE                 15569 non-null int64
TOT_POP_LESS19          15569 non-null int64
TOT_MALE_LESS19         15569 non-null int64
TOT_FEMALE_LESS19       15569 non-null int64
TOT_POP_20to39          15569 non-null int64
TOT_MALE_20to39         15569 non-null int64
TOT_FEMALE_20to39       15569 non-null int64
TOT_POP_40to59          15569 non-null int64
TOT_MALE_40to59         15569 non-null int64
TOT_FEMALE_40to59       15569 non-null int64
TOT_POP_Above60         15569 non-null int64
TOT_MALE_Above60        15569 non-null int64
TOT_FEMALE_Above60      15569 non-null int64
republican_candidate    15569 non-null object
democrat_candidate      15569 non-null object
republican_votes        15569 non-null float64
democrat_votes          15569 non-null float64
county_totalvotes       15569 non-null float64
winning candidate       15569 non-null object
winning party           15569 non-null object
avg_wage_salary         15569 non-null float64
AA_FEMALE%              15569 non-null float64
AA_MALE%                15569 non-null float64
BA_FEMALE%              15569 non-null float64
BA_MALE%                15569 non-null float64
H_FEMALE%               15569 non-null float64
H_MALE%                 15569 non-null float64
IA_FEMALE%              15569 non-null float64
IA_MALE%                15569 non-null float64
NA_FEMALE%              15569 non-null float64
NA_MALE%                15569 non-null float64
WA_FEMALE%              15569 non-null float64
WA_MALE%                15569 non-null float64
TOT_FEMALE%             15569 non-null float64
TOT_MALE%               15569 non-null float64
TOT_POP_LESS19%         15569 non-null float64
TOT_POP_20to39%         15569 non-null float64
TOT_POP_40to59%         15569 non-null float64
TOT_POP_Above60%        15569 non-null float64
Unemployment_Rate       15569 non-null float64
winning_party_binary    15569 non-null uint8
house_winning_party     15536 non-null float64
senate_winning_party    15536 non-null float64
dtypes: float64(25), int64(32), object(6), uint8(1)
memory usage: 7.6+ MB

In [62]:
# rename columns
renameCombinedCols = ['ID','YEAR_FIPS', 'YEAR', 'STATE_FIPS', 'COUNTY_FIPS', 'STATE', 'COUNTY',
       'AA_FEMALE', 'AA_MALE', 'BA_FEMALE', 'BA_MALE', 'H_FEMALE', 'H_MALE',
       'IA_FEMALE', 'IA_MALE', 'NA_FEMALE', 'NA_MALE', 'TOT_FEMALE',
       'TOT_MALE', 'TOT_POP', 'WA_FEMALE', 'WA_MALE', 'TOT_POP_LESS19',
       'TOT_MALE_LESS19', 'TOT_FEMALE_LESS19', 'TOT_POP_20to39',
       'TOT_MALE_20to39', 'TOT_FEMALE_20to39', 'TOT_POP_40to59',
       'TOT_MALE_40to59', 'TOT_FEMALE_40to59', 'TOT_POP_Above60',
       'TOT_MALE_Above60', 'TOT_FEMALE_Above60',
       'REP_CANDIDATE', 'DEM_CANDIDATE', 'REP_VOTES',
       'DEM_VOTES', 'COUNTY_TOTALVOTES', 'WINNING_CANDIDATE',
       'WINNING_PARTY', 'AVG_WAGE_SALARY', 'AA_FEMALE%', 'AA_MALE%',
       'BA_FEMALE%', 'BA_MALE%', 'H_FEMALE%', 'H_MALE%', 'IA_FEMALE%',
       'IA_MALE%', 'NA_FEMALE%', 'NA_MALE%', 'WA_FEMALE%', 'WA_MALE%',
       'TOT_FEMALE%', 'TOT_MALE%', 'TOT_POP_LESS19%', 'TOT_POP_20to39%',
       'TOT_POP_40to59%', 'TOT_POP_Above60%', 'UNEMPLOYMENT_RATE',
       'WINNING_PARTY_BINARY', 'HOUSE_WINNING_BINARY', 'SENATE_WINNING_BINARY']

len(renameCombinedCols)
combined_df.columns = renameCombinedCols
combined_df.head()

,ID,YEAR_FIPS,YEAR,STATE_FIPS,COUNTY_FIPS,STATE,COUNTY,AA_FEMALE,AA_MALE,BA_FEMALE,...,TOT_FEMALE%,TOT_MALE%,TOT_POP_LESS19%,TOT_POP_20to39%,TOT_POP_40to59%,TOT_POP_Above60%,UNEMPLOYMENT_RATE,WINNING_PARTY_BINARY,HOUSE_WINNING_BINARY,SENATE_WINNING_BINARY
0,0,20121001,2012,1,1,Alabama,Autauga County,296,201,5152,...,0.512912,0.487088,0.293056,0.252858,0.282427,0.171659,6.9,1,1.0,1.0
1,1,20121003,2012,1,3,Alabama,Baldwin County,833,551,8913,...,0.510581,0.489419,0.253453,0.230183,0.282293,0.234071,7.5,1,1.0,1.0
2,2,20121005,2012,1,5,Alabama,Barbour County,59,59,6111,...,0.469301,0.530699,0.242225,0.270801,0.278741,0.208233,11.5,0,1.0,1.0
3,3,20121007,2012,1,7,Alabama,Bibb County,10,12,1972,...,0.463799,0.536201,0.248820,0.283097,0.280955,0.187128,8.5,1,1.0,1.0
4,4,20121009,2012,1,9,Alabama,Blount County,82,48,390,...,0.505255,0.494745,0.271033,0.241682,0.276594,0.210691,6.9,1,1.0,1.0

In [63]:
# reorder columns
reorderCombinedCols = ['ID','YEAR_FIPS', 'YEAR', 'STATE_FIPS', 'COUNTY_FIPS', 'STATE', 'COUNTY',
                            'REP_CANDIDATE', 'DEM_CANDIDATE', 'REP_VOTES', 'DEM_VOTES', 'COUNTY_TOTALVOTES', 'WINNING_CANDIDATE',
                            'WINNING_PARTY', 'WINNING_PARTY_BINARY', 'HOUSE_WINNING_BINARY', 'SENATE_WINNING_BINARY','UNEMPLOYMENT_RATE',
                            'AVG_WAGE_SALARY', 'AA_FEMALE', 'AA_MALE', 'BA_FEMALE', 'BA_MALE', 'H_FEMALE', 'H_MALE',
                            'IA_FEMALE', 'IA_MALE', 'NA_FEMALE', 'NA_MALE', 'TOT_FEMALE', 'TOT_MALE', 'TOT_POP', 
                            'WA_FEMALE', 'WA_MALE', 'TOT_POP_LESS19', 'TOT_MALE_LESS19', 'TOT_FEMALE_LESS19', 
                            'TOT_POP_20to39', 'TOT_MALE_20to39', 'TOT_FEMALE_20to39', 'TOT_POP_40to59', 'TOT_MALE_40to59', 
                            'TOT_FEMALE_40to59', 'TOT_POP_Above60', 'TOT_MALE_Above60', 'TOT_FEMALE_Above60', 'AA_FEMALE%', 
                            'AA_MALE%', 'BA_FEMALE%', 'BA_MALE%', 'H_FEMALE%', 'H_MALE%', 'IA_FEMALE%', 'IA_MALE%', 
                            'NA_FEMALE%', 'NA_MALE%', 'WA_FEMALE%', 'WA_MALE%', 'TOT_FEMALE%', 'TOT_MALE%', 'TOT_POP_LESS19%', 
                            'TOT_POP_20to39%', 'TOT_POP_40to59%', 'TOT_POP_Above60%']

combined_df = combined_df[['ID','YEAR_FIPS', 'YEAR', 'STATE_FIPS', 'COUNTY_FIPS', 'STATE', 'COUNTY',
                            'REP_CANDIDATE', 'DEM_CANDIDATE', 'REP_VOTES', 'DEM_VOTES', 'COUNTY_TOTALVOTES', 'WINNING_CANDIDATE',
                            'WINNING_PARTY', 'WINNING_PARTY_BINARY', 'HOUSE_WINNING_BINARY', 'SENATE_WINNING_BINARY','UNEMPLOYMENT_RATE',
                            'AVG_WAGE_SALARY', 'AA_FEMALE', 'AA_MALE', 'BA_FEMALE', 'BA_MALE', 'H_FEMALE', 'H_MALE',
                            'IA_FEMALE', 'IA_MALE', 'NA_FEMALE', 'NA_MALE', 'TOT_FEMALE', 'TOT_MALE', 'TOT_POP', 
                            'WA_FEMALE', 'WA_MALE', 'TOT_POP_LESS19', 'TOT_MALE_LESS19', 'TOT_FEMALE_LESS19', 
                            'TOT_POP_20to39', 'TOT_MALE_20to39', 'TOT_FEMALE_20to39', 'TOT_POP_40to59', 'TOT_MALE_40to59', 
                            'TOT_FEMALE_40to59', 'TOT_POP_Above60', 'TOT_MALE_Above60', 'TOT_FEMALE_Above60', 'AA_FEMALE%', 
                            'AA_MALE%', 'BA_FEMALE%', 'BA_MALE%', 'H_FEMALE%', 'H_MALE%', 'IA_FEMALE%', 'IA_MALE%', 
                            'NA_FEMALE%', 'NA_MALE%', 'WA_FEMALE%', 'WA_MALE%', 'TOT_FEMALE%', 'TOT_MALE%', 'TOT_POP_LESS19%', 
                            'TOT_POP_20to39%', 'TOT_POP_40to59%', 'TOT_POP_Above60%']]

In [64]:
# check out final combined dataset
combined_df.head()

,ID,YEAR_FIPS,YEAR,STATE_FIPS,COUNTY_FIPS,STATE,COUNTY,REP_CANDIDATE,DEM_CANDIDATE,REP_VOTES,...,NA_FEMALE%,NA_MALE%,WA_FEMALE%,WA_MALE%,TOT_FEMALE%,TOT_MALE%,TOT_POP_LESS19%,TOT_POP_20to39%,TOT_POP_40to59%,TOT_POP_Above60%
0,0,20121001,2012,1,1,Alabama,Autauga County,Mitt Romney,Barack Obama,17379.0,...,0.000310,0.000511,0.402747,0.390054,0.512912,0.487088,0.293056,0.252858,0.282427,0.171659
1,1,20121003,2012,1,3,Alabama,Baldwin County,Mitt Romney,Barack Obama,66016.0,...,0.000300,0.000399,0.446461,0.429892,0.510581,0.489419,0.253453,0.230183,0.282293,0.234071
2,2,20121005,2012,1,5,Alabama,Barbour County,Mitt Romney,Barack Obama,5550.0,...,0.000622,0.001061,0.237175,0.271277,0.469301,0.530699,0.242225,0.270801,0.278741,0.208233
3,3,20121007,2012,1,7,Alabama,Bibb County,Mitt Romney,Barack Obama,6132.0,...,0.000219,0.001137,0.371240,0.394981,0.463799,0.536201,0.248820,0.283097,0.280955,0.187128
4,4,20121009,2012,1,9,Alabama,Blount County,Mitt Romney,Barack Obama,20757.0,...,0.000436,0.000627,0.487947,0.477838,0.505255,0.494745,0.271033,0.241682,0.276594,0.210691

In [65]:
# see how many nulls there are within dataframe
combined_df.isnull().sum()

ID                        0
YEAR_FIPS                 0
YEAR                      0
STATE_FIPS                0
COUNTY_FIPS               0
STATE                     0
COUNTY                    0
REP_CANDIDATE             0
DEM_CANDIDATE             0
REP_VOTES                 0
DEM_VOTES                 0
COUNTY_TOTALVOTES         0
WINNING_CANDIDATE         0
WINNING_PARTY             0
WINNING_PARTY_BINARY      0
HOUSE_WINNING_BINARY     33
SENATE_WINNING_BINARY    33
UNEMPLOYMENT_RATE         0
AVG_WAGE_SALARY           0
AA_FEMALE                 0
AA_MALE                   0
BA_FEMALE                 0
BA_MALE                   0
H_FEMALE                  0
H_MALE                    0
IA_FEMALE                 0
IA_MALE                   0
NA_FEMALE                 0
NA_MALE                   0
TOT_FEMALE                0
                         ..
TOT_POP_LESS19            0
TOT_MALE_LESS19           0
TOT_FEMALE_LESS19         0
TOT_POP_20to39            0
TOT_MALE_20to39           0
TOT_FEMALE_20to39         0
TOT_POP_40to59            0
TOT_MALE_40to59           0
TOT_FEMALE_40to59         0
TOT_POP_Above60           0
TOT_MALE_Above60          0
TOT_FEMALE_Above60        0
AA_FEMALE%                0
AA_MALE%                  0
BA_FEMALE%                0
BA_MALE%                  0
H_FEMALE%                 0
H_MALE%                   0
IA_FEMALE%                0
IA_MALE%                  0
NA_FEMALE%                0
NA_MALE%                  0
WA_FEMALE%                0
WA_MALE%                  0
TOT_FEMALE%               0
TOT_MALE%                 0
TOT_POP_LESS19%           0
TOT_POP_20to39%           0
TOT_POP_40to59%           0
TOT_POP_Above60%          0
Length: 64, dtype: int64

In [66]:
combined_df["HOUSE_WINNING_BINARY"].fillna(-1, inplace = True)
combined_df["SENATE_WINNING_BINARY"].fillna(-1, inplace = True)

In [67]:
#converting House winning binary and State Winnng binary to integers
convert_dict = {'HOUSE_WINNING_BINARY': int, 
                'SENATE_WINNING_BINARY': int
               } 
  
combined_df = combined_df.astype(convert_dict)

In [68]:
#Adding Margin of victory for plotting - Ranging from Red to Blue
combined_df['MARGIN_VICTORY']=(combined_df['DEM_VOTES']/combined_df['COUNTY_TOTALVOTES'])-(combined_df['REP_VOTES']/combined_df['COUNTY_TOTALVOTES'])

### Save one hot encoded dataframe to csv file

In [69]:
# output one hot encoded dataframe with null values to csv file
combined_df.to_csv("combined_jun27.csv")

## Merge senate and house election dataset to F20 Dataset

In [105]:
# verify dataset dimensions before merge
print("F20 demographic: {}".format(F20_df.shape))

F20 demographic: (3142, 65)

In [106]:
# merge dataframes on election year and state fips code
combined_df_20 = pd.merge(F20_df, F20_house_senate, how="left", 
                       left_on=["YEAR", "STATE"], right_on=["year", "state_fips"])

In [107]:
print("Combined F20 dataset dimensions: {}".format(combined_df_20.shape))
combined_df_20.head()

Combined F20 dataset dimensions: (3142, 71)

,Unnamed: 0,ID,AGEGRP,FIPS_x,YEAR,STATE,COUNTY,STNAME,CTYNAME,AA_FEMALE,...,TOT_POP_40to59%,TOT_POP_Above60%,Unemployment_Rate,winning_party_binary,year,state_x,state_fips,house_winning_party,state_y,senate_winning_party
0,632,20201001,Total,1001,2020,1,1,Alabama,Autauga County,380,...,0.275535,0.213845,NaN,0,2020.0,Alabama,1.0,1.0,NaN,-1.0
1,633,20201003,Total,1003,2020,1,3,Alabama,Baldwin County,1575,...,0.262928,0.276284,NaN,0,2020.0,Alabama,1.0,1.0,NaN,-1.0
2,634,20201005,Total,1005,2020,1,5,Alabama,Barbour County,61,...,0.255295,0.255938,NaN,0,2020.0,Alabama,1.0,1.0,NaN,-1.0
3,635,20201007,Total,1007,2020,1,7,Alabama,Bibb County,34,...,0.274687,0.225580,NaN,0,2020.0,Alabama,1.0,1.0,NaN,-1.0
4,636,20201009,Total,1009,2020,1,9,Alabama,Blount County,103,...,0.264834,0.246041,NaN,0,2020.0,Alabama,1.0,1.0,NaN,-1.0

In [108]:
combined_df_20.columns

Index(['Unnamed: 0', 'ID', 'AGEGRP', 'FIPS_x', 'YEAR', 'STATE', 'COUNTY',
       'STNAME', 'CTYNAME', 'AA_FEMALE', 'AA_MALE', 'BA_FEMALE', 'BA_MALE',
       'H_FEMALE', 'H_MALE', 'IA_FEMALE', 'IA_MALE', 'NA_FEMALE', 'NA_MALE',
       'SUMLEV', 'TOT_FEMALE', 'TOT_MALE', 'TOT_POP', 'WA_FEMALE', 'WA_MALE',
       'TOT_POP_LESS19', 'TOT_MALE_LESS19', 'TOT_FEMALE_LESS19',
       'TOT_POP_20to39', 'TOT_MALE_20to39', 'TOT_FEMALE_20to39',
       'TOT_POP_40to59', 'TOT_MALE_40to59', 'TOT_FEMALE_40to59',
       'TOT_POP_Above60', 'TOT_MALE_Above60', 'TOT_FEMALE_Above60',
       'republican_candidate', 'democrat_candidate', 'republican_votes',
       'democrat_votes', 'county_totalvotes', 'winning candidate',
       'winning party', 'avg_wage_salary', 'AA_FEMALE%', 'AA_MALE%',
       'BA_FEMALE%', 'BA_MALE%', 'H_FEMALE%', 'H_MALE%', 'IA_FEMALE%',
       'IA_MALE%', 'NA_FEMALE%', 'NA_MALE%', 'WA_FEMALE%', 'WA_MALE%',
       'TOT_FEMALE%', 'TOT_MALE%', 'TOT_POP_LESS19%', 'TOT_POP_20to39%',
       'TOT_POP_40to59%', 'TOT_POP_Above60%', 'Unemployment_Rate',
       'winning_party_binary', 'year', 'state_x', 'state_fips',
       'house_winning_party', 'state_y', 'senate_winning_party'],
      dtype='object')

In [109]:
combined_df_20 = combined_df_20.drop(dropCombinedCols,axis=1)

In [110]:
combined_df_20.columns = renameCombinedCols
combined_df_20.head()

,ID,YEAR_FIPS,YEAR,STATE_FIPS,COUNTY_FIPS,STATE,COUNTY,AA_FEMALE,AA_MALE,BA_FEMALE,...,TOT_FEMALE%,TOT_MALE%,TOT_POP_LESS19%,TOT_POP_20to39%,TOT_POP_40to59%,TOT_POP_Above60%,UNEMPLOYMENT_RATE,WINNING_PARTY_BINARY,HOUSE_WINNING_BINARY,SENATE_WINNING_BINARY
0,632,20201001,2020,1,1,Alabama,Autauga County,380,301,5762,...,0.514487,0.485513,0.259420,0.251201,0.275535,0.213845,NaN,0,1.0,-1.0
1,633,20201003,2020,1,3,Alabama,Baldwin County,1575,933,10092,...,0.515384,0.484616,0.236994,0.223794,0.262928,0.276284,NaN,0,1.0,-1.0
2,634,20201005,2020,1,5,Alabama,Barbour County,61,52,5672,...,0.472168,0.527832,0.228769,0.259998,0.255295,0.255938,NaN,0,1.0,-1.0
3,635,20201007,2020,1,7,Alabama,Bibb County,34,19,1816,...,0.467813,0.532188,0.225536,0.274196,0.274687,0.225580,NaN,0,1.0,-1.0
4,636,20201009,2020,1,9,Alabama,Blount County,103,82,443,...,0.507261,0.492739,0.253544,0.235581,0.264834,0.246041,NaN,0,1.0,-1.0

In [111]:
# reorder columns
reorderCombinedCols = ['ID','YEAR_FIPS', 'YEAR', 'STATE_FIPS', 'COUNTY_FIPS', 'STATE', 'COUNTY',
                            'REP_CANDIDATE', 'DEM_CANDIDATE', 'REP_VOTES', 'DEM_VOTES', 'COUNTY_TOTALVOTES', 'WINNING_CANDIDATE',
                            'WINNING_PARTY', 'WINNING_PARTY_BINARY', 'HOUSE_WINNING_BINARY', 'SENATE_WINNING_BINARY','UNEMPLOYMENT_RATE',
                            'AVG_WAGE_SALARY', 'AA_FEMALE', 'AA_MALE', 'BA_FEMALE', 'BA_MALE', 'H_FEMALE', 'H_MALE',
                            'IA_FEMALE', 'IA_MALE', 'NA_FEMALE', 'NA_MALE', 'TOT_FEMALE', 'TOT_MALE', 'TOT_POP', 
                            'WA_FEMALE', 'WA_MALE', 'TOT_POP_LESS19', 'TOT_MALE_LESS19', 'TOT_FEMALE_LESS19', 
                            'TOT_POP_20to39', 'TOT_MALE_20to39', 'TOT_FEMALE_20to39', 'TOT_POP_40to59', 'TOT_MALE_40to59', 
                            'TOT_FEMALE_40to59', 'TOT_POP_Above60', 'TOT_MALE_Above60', 'TOT_FEMALE_Above60', 'AA_FEMALE%', 
                            'AA_MALE%', 'BA_FEMALE%', 'BA_MALE%', 'H_FEMALE%', 'H_MALE%', 'IA_FEMALE%', 'IA_MALE%', 
                            'NA_FEMALE%', 'NA_MALE%', 'WA_FEMALE%', 'WA_MALE%', 'TOT_FEMALE%', 'TOT_MALE%', 'TOT_POP_LESS19%', 
                            'TOT_POP_20to39%', 'TOT_POP_40to59%', 'TOT_POP_Above60%']

combined_df_20 = combined_df_20[['ID','YEAR_FIPS', 'YEAR', 'STATE_FIPS', 'COUNTY_FIPS', 'STATE', 'COUNTY',
                            'REP_CANDIDATE', 'DEM_CANDIDATE', 'REP_VOTES', 'DEM_VOTES', 'COUNTY_TOTALVOTES', 'WINNING_CANDIDATE',
                            'WINNING_PARTY', 'WINNING_PARTY_BINARY', 'HOUSE_WINNING_BINARY', 'SENATE_WINNING_BINARY','UNEMPLOYMENT_RATE',
                            'AVG_WAGE_SALARY', 'AA_FEMALE', 'AA_MALE', 'BA_FEMALE', 'BA_MALE', 'H_FEMALE', 'H_MALE',
                            'IA_FEMALE', 'IA_MALE', 'NA_FEMALE', 'NA_MALE', 'TOT_FEMALE', 'TOT_MALE', 'TOT_POP', 
                            'WA_FEMALE', 'WA_MALE', 'TOT_POP_LESS19', 'TOT_MALE_LESS19', 'TOT_FEMALE_LESS19', 
                            'TOT_POP_20to39', 'TOT_MALE_20to39', 'TOT_FEMALE_20to39', 'TOT_POP_40to59', 'TOT_MALE_40to59', 
                            'TOT_FEMALE_40to59', 'TOT_POP_Above60', 'TOT_MALE_Above60', 'TOT_FEMALE_Above60', 'AA_FEMALE%', 
                            'AA_MALE%', 'BA_FEMALE%', 'BA_MALE%', 'H_FEMALE%', 'H_MALE%', 'IA_FEMALE%', 'IA_MALE%', 
                            'NA_FEMALE%', 'NA_MALE%', 'WA_FEMALE%', 'WA_MALE%', 'TOT_FEMALE%', 'TOT_MALE%', 'TOT_POP_LESS19%', 
                            'TOT_POP_20to39%', 'TOT_POP_40to59%', 'TOT_POP_Above60%']]

In [112]:
# see how many nulls there are within dataframe
combined_df_20.isnull().sum()

ID                          0
YEAR_FIPS                   0
YEAR                        0
STATE_FIPS                  0
COUNTY_FIPS                 0
STATE                       0
COUNTY                      0
REP_CANDIDATE            3142
DEM_CANDIDATE            3142
REP_VOTES                3142
DEM_VOTES                3142
COUNTY_TOTALVOTES        3142
WINNING_CANDIDATE        3142
WINNING_PARTY            3142
WINNING_PARTY_BINARY        0
HOUSE_WINNING_BINARY        1
SENATE_WINNING_BINARY       1
UNEMPLOYMENT_RATE        3142
AVG_WAGE_SALARY          3142
AA_FEMALE                   0
AA_MALE                     0
BA_FEMALE                   0
BA_MALE                     0
H_FEMALE                    0
H_MALE                      0
IA_FEMALE                   0
IA_MALE                     0
NA_FEMALE                   0
NA_MALE                     0
TOT_FEMALE                  0
                         ...
TOT_POP_LESS19              0
TOT_MALE_LESS19             0
TOT_FEMALE_LESS19           0
TOT_POP_20to39              0
TOT_MALE_20to39             0
TOT_FEMALE_20to39           0
TOT_POP_40to59              0
TOT_MALE_40to59             0
TOT_FEMALE_40to59           0
TOT_POP_Above60             0
TOT_MALE_Above60            0
TOT_FEMALE_Above60          0
AA_FEMALE%                  0
AA_MALE%                    0
BA_FEMALE%                  0
BA_MALE%                    0
H_FEMALE%                   0
H_MALE%                     0
IA_FEMALE%                  0
IA_MALE%                    0
NA_FEMALE%                  0
NA_MALE%                    0
WA_FEMALE%                  0
WA_MALE%                    0
TOT_FEMALE%                 0
TOT_MALE%                   0
TOT_POP_LESS19%             0
TOT_POP_20to39%             0
TOT_POP_40to59%             0
TOT_POP_Above60%            0
Length: 64, dtype: int64

In [113]:
#copying 2016 unemployment data and average wage salary into 2020
election_years = [2016]

F16_df = merged_df[merged_df["YEAR"].isin(election_years)]
print("2016 data dimensions: {}".format(F16_df.shape))

2016 data dimensions: (3142, 65)

In [114]:
F16_df.head(10)

,Unnamed: 0,ID,AGEGRP,FIPS_x,YEAR,STATE,COUNTY,STNAME,CTYNAME,AA_FEMALE,...,WA_FEMALE%,WA_MALE%,TOT_FEMALE%,TOT_MALE%,TOT_POP_LESS19%,TOT_POP_20to39%,TOT_POP_40to59%,TOT_POP_Above60%,Unemployment_Rate,winning_party_binary
316,316,20161001,Total,1001,2016,1,1,Alabama,Autauga County,337,...,0.398006,0.384230,0.511918,0.488082,0.272432,0.250747,0.286373,0.190448,5.1,1
317,317,20161003,Total,1003,2016,1,3,Alabama,Baldwin County,1154,...,0.445843,0.426208,0.512247,0.487753,0.244050,0.228220,0.276195,0.251535,5.3,1
318,318,20161005,Total,1005,2016,1,5,Alabama,Barbour County,55,...,0.233052,0.266799,0.467673,0.532327,0.231706,0.269639,0.269340,0.229315,8.3,1
319,319,20161007,Total,1007,2016,1,7,Alabama,Bibb County,23,...,0.373275,0.394348,0.461470,0.538530,0.229759,0.276696,0.287698,0.205847,6.4,1
320,320,20161009,Total,1009,2016,1,9,Alabama,Blount County,93,...,0.487161,0.474314,0.506806,0.493194,0.258097,0.235566,0.274908,0.231429,5.4,1
321,321,20161011,Total,1011,2016,1,11,Alabama,Bullock County,10,...,0.100422,0.161275,0.453633,0.546367,0.229161,0.281294,0.280075,0.209470,6.8,0
322,322,20161013,Total,1013,2016,1,13,Alabama,Butler County,106,...,0.279703,0.253453,0.535516,0.464484,0.252913,0.239542,0.256648,0.250897,6.9,1
323,323,20161015,Total,1015,2016,1,15,Alabama,Calhoun County,626,...,0.389844,0.368490,0.519169,0.480831,0.247321,0.261761,0.266624,0.224294,6.5,1
324,324,20161017,Total,1017,2016,1,17,Alabama,Chambers County,153,...,0.297763,0.281313,0.520718,0.479282,0.235727,0.235786,0.278458,0.250029,5.4,1
325,325,20161019,Total,1019,2016,1,19,Alabama,Cherokee County,47,...,0.468960,0.463787,0.502162,0.497838,0.225041,0.206625,0.286928,0.281407,5.0,1

In [115]:
combined_df_20.head(10)

,ID,YEAR_FIPS,YEAR,STATE_FIPS,COUNTY_FIPS,STATE,COUNTY,REP_CANDIDATE,DEM_CANDIDATE,REP_VOTES,...,NA_FEMALE%,NA_MALE%,WA_FEMALE%,WA_MALE%,TOT_FEMALE%,TOT_MALE%,TOT_POP_LESS19%,TOT_POP_20to39%,TOT_POP_40to59%,TOT_POP_Above60%
0,632,20201001,2020,1,1,Alabama,Autauga County,NaN,NaN,NaN,...,0.000522,0.000594,0.392097,0.375155,0.514487,0.485513,0.259420,0.251201,0.275535,0.213845
1,633,20201003,2020,1,3,Alabama,Baldwin County,NaN,NaN,NaN,...,0.000335,0.000335,0.448716,0.424136,0.515384,0.484616,0.236994,0.223794,0.262928,0.276284
2,634,20201005,2020,1,5,Alabama,Barbour County,NaN,NaN,NaN,...,0.000643,0.001206,0.233069,0.257626,0.472168,0.527832,0.228769,0.259998,0.255295,0.255938
3,635,20201007,2020,1,7,Alabama,Bibb County,NaN,NaN,NaN,...,0.000179,0.000982,0.377188,0.391161,0.467813,0.532188,0.225536,0.274196,0.274687,0.225580
4,636,20201009,2020,1,9,Alabama,Blount County,NaN,NaN,NaN,...,0.000450,0.000761,0.486670,0.472113,0.507261,0.492739,0.253544,0.235581,0.264834,0.246041
5,637,20201011,2020,1,11,Alabama,Bullock County,NaN,NaN,NaN,...,0.003551,0.003946,0.103176,0.159302,0.454823,0.545177,0.229631,0.280233,0.259420,0.230716
6,638,20201013,2020,1,13,Alabama,Butler County,NaN,NaN,NaN,...,0.000254,0.000254,0.273577,0.248933,0.534299,0.465701,0.244512,0.234909,0.244360,0.276220
7,639,20201015,2020,1,15,Alabama,Calhoun County,NaN,NaN,NaN,...,0.000560,0.000543,0.387375,0.365410,0.519466,0.480534,0.243076,0.256640,0.254224,0.246060
8,640,20201017,2020,1,17,Alabama,Chambers County,NaN,NaN,NaN,...,0.000149,0.000297,0.294244,0.276394,0.521255,0.478745,0.228499,0.241380,0.262948,0.267172
9,641,20201019,2020,1,19,Alabama,Cherokee County,NaN,NaN,NaN,...,0.000115,0.000192,0.469960,0.460318,0.504610,0.495390,0.212623,0.205747,0.271858,0.309773

In [116]:
F16_df.columns

Index(['Unnamed: 0', 'ID', 'AGEGRP', 'FIPS_x', 'YEAR', 'STATE', 'COUNTY',
       'STNAME', 'CTYNAME', 'AA_FEMALE', 'AA_MALE', 'BA_FEMALE', 'BA_MALE',
       'H_FEMALE', 'H_MALE', 'IA_FEMALE', 'IA_MALE', 'NA_FEMALE', 'NA_MALE',
       'SUMLEV', 'TOT_FEMALE', 'TOT_MALE', 'TOT_POP', 'WA_FEMALE', 'WA_MALE',
       'TOT_POP_LESS19', 'TOT_MALE_LESS19', 'TOT_FEMALE_LESS19',
       'TOT_POP_20to39', 'TOT_MALE_20to39', 'TOT_FEMALE_20to39',
       'TOT_POP_40to59', 'TOT_MALE_40to59', 'TOT_FEMALE_40to59',
       'TOT_POP_Above60', 'TOT_MALE_Above60', 'TOT_FEMALE_Above60',
       'republican_candidate', 'democrat_candidate', 'republican_votes',
       'democrat_votes', 'county_totalvotes', 'winning candidate',
       'winning party', 'avg_wage_salary', 'AA_FEMALE%', 'AA_MALE%',
       'BA_FEMALE%', 'BA_MALE%', 'H_FEMALE%', 'H_MALE%', 'IA_FEMALE%',
       'IA_MALE%', 'NA_FEMALE%', 'NA_MALE%', 'WA_FEMALE%', 'WA_MALE%',
       'TOT_FEMALE%', 'TOT_MALE%', 'TOT_POP_LESS19%', 'TOT_POP_20to39%',
       'TOT_POP_40to59%', 'TOT_POP_Above60%', 'Unemployment_Rate',
       'winning_party_binary'],
      dtype='object')

In [118]:
# output one hot encoded dataframe with null values to csv file
combined_df_20.to_csv("F20_jun27.csv")

In [119]:
# output one hot encoded dataframe with null values to csv file
F16_df.to_csv("F16_jun27.csv")

In [120]:
# counties that flipped between the two parties in the last 20 years.
state_county_map = {}
county_groupby = combined_df.groupby("COUNTY_FIPS")
count = 0
for name, group in county_groupby:
    winning_party = None
    prev_winning_party = None
    for index, row in group.iterrows():
        winning_party = row['WINNING_PARTY']
        
        if prev_winning_party == None:
            prev_winning_party = winning_party
        
        if prev_winning_party != winning_party:
            #break and move to next county...
            #print("training set add: raw: state={}, county={}".format(raw['STATE'], raw['COUNTY']))
            count +=1
            state_county_map[str(row['STATE_FIPS']) + '_' + str(row['COUNTY_FIPS'])] = 1
            break

print(count)

151

In [121]:
#Creating the train Data
#add new column to help us identify county/state combo that should be used in training. 
count_0 = 0
count_1 = 0
combined_df["TRAIN"] = ""
for index, row in combined_df.iterrows():
    state_fips = row['STATE_FIPS']
    county_fips = row['COUNTY_FIPS']
    
    key = str(state_fips) + '_' + str(county_fips)
    
    if state_county_map.get(key) == None:
        combined_df['TRAIN'][index] = 0
        count_0 += 1
    else:
        combined_df['TRAIN'][index] = 1
        count_1 += 1
    
print(count_0)
print(count_1)

C:\Users\nerella\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  del sys.path[0]
C:\Users\nerella\Anaconda3\lib\site-packages\ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()

14815
754

In [122]:
combined_df.loc[combined_df['TRAIN'] == 1]

,ID,YEAR_FIPS,YEAR,STATE_FIPS,COUNTY_FIPS,STATE,COUNTY,REP_CANDIDATE,DEM_CANDIDATE,REP_VOTES,...,WA_FEMALE%,WA_MALE%,TOT_FEMALE%,TOT_MALE%,TOT_POP_LESS19%,TOT_POP_20to39%,TOT_POP_40to59%,TOT_POP_Above60%,MARGIN_VICTORY,TRAIN
68,68,20122016,2012,2,16,Alaska,Aleutians West Census Area,Mitt Romney,Barack Obama,2876.0,...,0.119784,0.293165,0.328957,0.671043,0.161511,0.319604,0.423381,0.095504,0.158334,1
69,69,20122020,2012,2,20,Alaska,Anchorage Municipality,Mitt Romney,Barack Obama,4544.0,...,0.326917,0.352548,0.491916,0.508084,0.287794,0.307180,0.284024,0.121002,-0.183702,1
70,96,20124001,2012,4,1,Arizona,Apache County,Mitt Romney,Barack Obama,8250.0,...,0.119278,0.126086,0.501100,0.498900,0.350192,0.231540,0.250487,0.167780,0.344205,1
75,101,20124011,2012,4,11,Arizona,Greenlee County,Mitt Romney,Barack Obama,1592.0,...,0.443591,0.486558,0.477676,0.522324,0.315050,0.243879,0.268003,0.173068,-0.094822,1
80,106,20124019,2012,4,19,Arizona,Pima County,Mitt Romney,Barack Obama,174779.0,...,0.440069,0.422924,0.508835,0.491165,0.262281,0.265497,0.257044,0.215178,0.069253,1
82,108,20124023,2012,4,23,Arizona,Santa Cruz County,Mitt Romney,Barack Obama,4235.0,...,0.509342,0.461767,0.523619,0.476381,0.336398,0.215437,0.259637,0.188528,0.377933,1
87,113,20125005,2012,5,5,Arkansas,Baxter County,Mitt Romney,Barack Obama,13688.0,...,0.504204,0.470381,0.517646,0.482354,0.199297,0.172798,0.262653,0.365253,-0.440354,1
93,119,20125017,2012,5,17,Arkansas,Chicot County,Mitt Romney,Barack Obama,1670.0,...,0.215085,0.224322,0.507881,0.492119,0.254407,0.227542,0.273390,0.244661,0.224490,1
105,131,20125041,2012,5,41,Arkansas,Desha County,Mitt Romney,Barack Obama,1896.0,...,0.256929,0.243882,0.531383,0.468617,0.285725,0.228055,0.272755,0.213464,0.123756,1
108,134,20125047,2012,5,47,Arkansas,Franklin County,Mitt Romney,Barack Obama,4631.0,...,0.483871,0.473284,0.504770,0.495230,0.271464,0.229336,0.271519,0.227681,-0.444190,1
116,142,20125063,2012,5,63,Arkansas,Independence County,Mitt Romney,Barack Obama,8728.0,...,0.484814,0.465689,0.509617,0.490383,0.268134,0.246998,0.268460,0.216409,-0.439380,1
117,143,20125065,2012,5,65,Arkansas,Izard County,Mitt Romney,Barack Obama,3575.0,...,0.472384,0.491912,0.485063,0.514937,0.211892,0.196080,0.277397,0.314631,-0.388594,1
119,145,20125069,2012,5,69,Arkansas,Jefferson County,Mitt Romney,Barack Obama,9520.0,...,0.208924,0.216243,0.507933,0.492067,0.272825,0.258589,0.277182,0.191404,0.290326,1
121,147,20125073,2012,5,73,Arkansas,Lafayette County,Mitt Romney,Barack Obama,1713.0,...,0.308879,0.302864,0.517589,0.482411,0.258794,0.202955,0.277102,0.261148,-0.184363,1
123,149,20125077,2012,5,77,Arkansas,Lee County,Mitt Romney,Barack Obama,1280.0,...,0.174202,0.252116,0.444498,0.555502,0.232205,0.267795,0.280492,0.219508,0.241530,1
127,153,20125085,2012,5,85,Arkansas,Lonoke County,Mitt Romney,Barack Obama,17880.0,...,0.459066,0.450102,0.507552,0.492448,0.298094,0.270489,0.269325,0.162093,-0.508211,1
128,154,20125087,2012,5,87,Arkansas,Madison County,Mitt Romney,Barack Obama,4263.0,...,0.479214,0.483168,0.498852,0.501148,0.267024,0.219969,0.291571,0.221436,-0.329476,1
130,156,20125091,2012,5,91,Arkansas,Miller County,Mitt Romney,Barack Obama,10622.0,...,0.361906,0.363008,0.507151,0.492849,0.268038,0.265995,0.269576,0.196391,-0.398199,1
135,161,20125101,2012,5,101,Arkansas,Newton County,Mitt Romney,Barack Obama,2508.0,...,0.474747,0.488456,0.495430,0.504570,0.228956,0.198413,0.288119,0.284512,-0.413821,1
137,163,20125105,2012,5,105,Arkansas,Perry County,Mitt Romney,Barack Obama,2581.0,...,0.482138,0.475050,0.503400,0.496600,0.255723,0.219040,0.292884,0.232353,-0.353987,1
138,164,20125107,2012,5,107,Arkansas,Phillips County,Mitt Romney,Barack Obama,2598.0,...,0.181629,0.171803,0.534554,0.465446,0.310436,0.219690,0.261026,0.208848,0.328373,1
141,167,20125113,2012,5,113,Arkansas,Polk County,Mitt Romney,Barack Obama,5955.0,...,0.484931,0.467370,0.507958,0.492042,0.261574,0.200522,0.271201,0.266702,-0.569376,1
146,172,20125123,2012,5,123,Arkansas,St. Francis County,Mitt Romney,Barack Obama,3368.0,...,0.196950,0.257847,0.454868,0.545132,0.259904,0.278879,0.280617,0.180599,0.184406,1
150,176,20125131,2012,5,131,Arkansas,Sebastian County,Mitt Romney,Barack Obama,29169.0,...,0.426547,0.410350,0.509792,0.490208,0.280747,0.260860,0.272588,0.185805,-0.370762,1
158,184,20125147,2012,5,147,Arkansas,Woodruff County,Mitt Romney,Barack Obama,1227.0,...,0.364740,0.339495,0.524762,0.475238,0.251897,0.210650,0.280728,0.256725,0.042086,1
161,187,20126003,2012,6,3,California,Alpine County,Mitt Romney,Barack Obama,236.0,...,0.362618,0.399655,0.484065,0.515935,0.235142,0.170543,0.358312,0.236003,0.234303,1
166,192,20126013,2012,6,13,California,Contra Costa County,Mitt Romney,Barack Obama,136517.0,...,0.349060,0.340981,0.512417,0.487583,0.273065,0.247953,0.296901,0.182081,0.352117,1
172,198,20126025,2012,6,25,California,Imperial County,Mitt Romney,Barack Obama,12777.0,...,0.443112,0.451891,0.486865,0.513135,0.325674,0.280003,0.247313,0.147010,0.320472,1
176,202,20126033,2012,6,33,California,Lake County,Mitt Romney,Barack Obama,9200.0,...,0.441044,0.442666,0.498432,0.501568,0.234819,0.205252,0.301861,0.258068,0.169424,1
177,203,20126035,2012,6,35,California,Lassen County,Mitt Romney,Barack Obama,7296.0,...,0.316031,0.505340,0.356712,0.643288,0.204237,0.344827,0.297944,0.152992,-0.397173,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15445,18731,20086013,2008,6,13,California,Contra Costa County,John McCain,Barack Obama,136436.0,...,0.358265,0.349952,0.512157,0.487843,0.280021,0.251612,0.299950,0.168417,0.377609,1
15451,18737,20086025,2008,6,25,California,Imperial County,John McCain,Barack Obama,14008.0,...,0.439324,0.457113,0.480953,0.519047,0.331114,0.284363,0.246695,0.137828,0.261566,1
15455,18741,20086033,2008,6,33,California,Lake County,John McCain,Barack Obama,9935.0,...,0.445729,0.447196,0.499774,0.500226,0.245564,0.203521,0.312312,0.238604,0.192585,1
15456,18742,20086035,2008,6,35,California,Lassen County,John McCain,Barack Obama,7483.0,...,0.313744,0.507567,0.350583,0.649417,0.209715,0.353643,0.300098,0.136544,-0.342232,1
15457,18743,20086037,2008,6,37,California,Los Angeles County,John McCain,Barack Obama,956425.0,...,0.362163,0.362798,0.506827,0.493173,0.286014,0.304326,0.265747,0.143912,0.403655,1
15461,18747,20086045,2008,6,45,California,Mendocino County,John McCain,Barack Obama,10721.0,...,0.441261,0.442237,0.500281,0.499719,0.252300,0.233258,0.300800,0.213642,0.427879,1
15464,18750,20086051,2008,6,51,California,Mono County,John McCain,Barack Obama,2354.0,...,0.430545,0.505776,0.462275,0.537725,0.240605,0.298655,0.325486,0.135254,0.132651,1
15465,18751,20086053,2008,6,53,California,Monterey County,John McCain,Barack Obama,38797.0,...,0.403518,0.429283,0.484196,0.515804,0.301847,0.298877,0.254414,0.144862,0.382608,1
15466,18752,20086055,2008,6,55,California,Napa County,John McCain,Barack Obama,19484.0,...,0.437032,0.435682,0.501542,0.498458,0.260712,0.246992,0.288016,0.204280,0.324687,1
15467,18753,20086057,2008,6,57,California,Nevada County,John McCain,Barack Obama,25663.0,...,0.478066,0.468556,0.505512,0.494488,0.227386,0.187834,0.327270,0.257511,0.053085,1
15472,18758,20086067,2008,6,67,California,Sacramento County,John McCain,Barack Obama,213583.0,...,0.343398,0.332885,0.509722,0.490278,0.290391,0.289067,0.270344,0.150198,0.190210,1
15474,18760,20086071,2008,6,71,California,San Bernardino County,John McCain,Barack Obama,277408.0,...,0.393793,0.396648,0.501285,0.498715,0.337418,0.286997,0.255895,0.119690,0.063186,1
15476,18762,20086075,2008,6,75,California,San Francisco County,John McCain,Barack Obama,52292.0,...,0.257221,0.290182,0.493962,0.506038,0.156360,0.374338,0.284320,0.184983,0.705021,1
15478,18764,20086079,2008,6,79,California,San Luis Obispo County,John McCain,Barack Obama,61055.0,...,0.445690,0.458199,0.487217,0.512783,0.241363,0.273041,0.286627,0.198969,0.053681,1
15479,18765,20086081,2008,6,81,California,San Mateo County,John McCain,Barack Obama,75057.0,...,0.332780,0.330707,0.508779,0.491221,0.244778,0.273267,0.300121,0.181834,0.487217,1
15480,18766,20086083,2008,6,83,California,Santa Barbara County,John McCain,Barack Obama,65585.0,...,0.435536,0.438575,0.498190,0.501810,0.281634,0.296895,0.251885,0.169586,0.228852,1
15486,18772,20086095,2008,6,95,California,Solano County,John McCain,Barack Obama,56035.0,...,0.304032,0.313987,0.498571,0.501429,0.285110,0.270307,0.292762,0.151821,0.286135,1
15487,18773,20086097,2008,6,97,California,Sonoma County,John McCain,Barack Obama,55127.0,...,0.451266,0.438390,0.507418,0.492582,0.256002,0.253130,0.303813,0.187054,0.496013,1
15488,18774,20086099,2008,6,99,California,Stanislaus County,John McCain,Barack Obama,77497.0,...,0.432911,0.424893,0.504691,0.495309,0.326945,0.277337,0.254483,0.141235,0.017278,1
15494,18780,20086111,2008,6,111,California,Ventura County,John McCain,Barack Obama,145853.0,...,0.432912,0.431440,0.502779,0.497221,0.296312,0.263066,0.284838,0.155783,0.122861,1
15504,18790,20088014,2008,8,14,Colorado,Broomfield County,John McCain,Barack Obama,12757.0,...,0.452898,0.448065,0.502678,0.497322,0.291911,0.261693,0.317393,0.129003,0.115812,1
15505,18791,20088015,2008,8,15,Colorado,Chaffee County,John McCain,Barack Obama,4873.0,...,0.456293,0.496633,0.471082,0.528918,0.195316,0.222248,0.327617,0.254820,-0.001210,1
15508,18794,20088021,2008,8,21,Colorado,Conejos County,John McCain,Barack Obama,1653.0,...,0.473896,0.472800,0.500913,0.499087,0.317999,0.205428,0.271145,0.205428,0.129324,1
15513,18799,20088031,2008,8,31,Colorado,Denver County,John McCain,Barack Obama,62567.0,...,0.402101,0.407892,0.499600,0.500400,0.241886,0.360159,0.250296,0.147659,0.524117,1
15527,18813,20088059,2008,8,59,Colorado,Jefferson County,John McCain,Barack Obama,131627.0,...,0.469883,0.461756,0.504240,0.495760,0.257110,0.251193,0.323371,0.168326,0.089900,1
15552,18838,20088109,2008,8,109,Colorado,Saguache County,John McCain,Barack Obama,953.0,...,0.466818,0.476903,0.495120,0.504880,0.261711,0.197788,0.336207,0.204294,0.282854,1
15556,18842,20088117,2008,8,117,Colorado,Summit County,John McCain,Barack Obama,4883.0,...,0.432320,0.529715,0.448897,0.551103,0.194715,0.390595,0.302410,0.112281,0.330156,1
15557,18843,20088119,2008,8,119,Colorado,Teller County,John McCain,Barack Obama,8146.0,...,0.468666,0.488087,0.490245,0.509755,0.241820,0.178403,0.400185,0.179592,-0.281497,1
15564,18850,20089007,2008,9,7,Connecticut,Middlesex County,John McCain,Barack Obama,32907.0,...,0.465518,0.445223,0.511756,0.488244,0.244606,0.228491,0.323946,0.202956,0.230153,1
15565,18851,20089009,2008,9,9,Connecticut,New Haven County,John McCain,Barack Obama,144465.0,...,0.419644,0.391785,0.518593,0.481407,0.261191,0.257549,0.290398,0.190863,0.231454,1

In [123]:
# output one hot encoded dataframe with null values to csv file
combined_df.to_csv("combined_jun27_train.csv")