In [24]:
import pandas as pd

In [25]:
electoral_ref = pd.read_excel('../../data/Electoral College Votes.xlsx')
data_2020 = pd.read_csv('../../data/F20_phase3_rfc_0707.csv')
data_historical = pd.read_csv("../../data/combined_jun22_train.csv", encoding = "ISO-8859-1")

In [26]:
### 1) create a new df with StateFips/Count

In [27]:
state_fips_map = {}
for index, row in data_historical.iterrows():
    #print(row)
    state = row['STATE']
    #print(type(state))
    if (state_fips_map.get(state) == None):
        state_fips_map[state] = row['STATE_FIPS']
    
print(state_fips_map)

{'Alabama': 1, 'Alaska': 2, 'Arizona': 4, 'Arkansas': 5, 'California': 6, 'Colorado': 8, 'Connecticut': 9, 'Delaware': 10, 'District of Columbia': 11, 'Florida': 12, 'Georgia': 13, 'Hawaii': 15, 'Idaho': 16, 'Illinois': 17, 'Indiana': 18, 'Iowa': 19, 'Kansas': 20, 'Kentucky': 21, 'Louisiana': 22, 'Maine': 23, 'Maryland': 24, 'Massachusetts': 25, 'Michigan': 26, 'Minnesota': 27, 'Mississippi': 28, 'Missouri': 29, 'Montana': 30, 'Nebraska': 31, 'Nevada': 32, 'New Hampshire': 33, 'New Jersey': 34, 'New Mexico': 35, 'New York': 36, 'North Carolina': 37, 'North Dakota': 38, 'Ohio': 39, 'Oklahoma': 40, 'Oregon': 41, 'Pennsylvania': 42, 'Rhode Island': 44, 'South Carolina': 45, 'South Dakota': 46, 'Tennessee': 47, 'Texas': 48, 'Utah': 49, 'Vermont': 50, 'Virginia': 51, 'Washington': 53, 'West Virginia': 54, 'Wisconsin': 55, 'Wyoming': 56}

In [28]:
state_fips_df = pd.DataFrame(list(state_fips_map.items()), columns=['STATE','STATE_FIPS'])

In [29]:
state_fips_df.head()

        STATE  STATE_FIPS
0     Alabama           1
1      Alaska           2
2     Arizona           4
3    Arkansas           5
4  California           6

In [30]:
df = electoral_ref.merge(state_fips_df, left_on='STATE', right_on='STATE')

In [31]:
df.head()

        STATE  COUNT  STATE_FIPS
0     Alabama      9           1
1      Alaska      3           2
2     Arizona     11           4
3    Arkansas      6           5
4  California     55           6

In [32]:
data_2020.loc[data_2020['STATE_FIPS'] == 13]

,Unnamed: 0,YEAR,STATE_FIPS,COUNTY_FIPS,HOUSE_WINNING_BINARY,SENATE_WINNING_BINARY,UNEMPLOYMENT_RATE,AVG_WAGE_SALARY,AA_FEMALE,AA_MALE,...,TOT_MALE%,TOT_POP_LESS19%,TOT_POP_20to39%,TOT_POP_40to59%,TOT_POP_Above60%,COUNTY_TOTALVOTES,REP_VOTES%,DEM_VOTES%,REP_VOTES,DEM_VOTES
387,387,2020,13,1,0,-1,6.3,34006,58,97,...,0.499271,0.269898,0.238288,0.252067,0.239747,8400,0.637239,0.362761,5352,3047
388,388,2020,13,3,0,-1,4.3,0,27,47,...,0.504761,0.286971,0.257684,0.258166,0.197180,2617,0.393208,0.606792,1029,1587
389,389,2020,13,5,0,-1,5.5,0,43,32,...,0.488869,0.276531,0.246848,0.251140,0.225481,6142,0.392948,0.607052,2413,3728
390,390,2020,13,7,0,-1,10.4,0,15,19,...,0.494502,0.211837,0.216041,0.266494,0.305627,4312,0.393303,0.606697,1695,2616
391,391,2020,13,9,0,-1,6.6,109924,381,375,...,0.507373,0.250474,0.294626,0.232068,0.222832,23495,0.391244,0.608756,9192,14302
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
541,541,2020,13,313,0,-1,7.3,74584,872,779,...,0.498241,0.284773,0.264025,0.257154,0.194048,40061,0.411302,0.588698,16477,23583
542,542,2020,13,315,0,-1,5.1,0,25,41,...,0.597367,0.210395,0.286995,0.262823,0.239787,4256,0.660398,0.339602,2810,1445
543,543,2020,13,317,0,-1,4.1,0,42,43,...,0.480053,0.233900,0.207270,0.250101,0.308728,8587,0.660045,0.339955,5667,2919
544,544,2020,13,319,0,-1,3.1,0,23,18,...,0.478420,0.249668,0.223882,0.252767,0.273683,8097,0.660246,0.339754,5346,2750
545,545,2020,13,321,0,-1,3.4,34933,84,52,...,0.480418,0.244692,0.232819,0.261885,0.260604,13914,0.659722,0.340278,9179,4734

In [33]:
data_2020.drop('Unnamed: 0', inplace=True, axis=1)

In [168]:
## 2) 

# create map of visited county_state
# create map of D electoral votes, R electoral votes
# loop over data_2020
# updaste the two maps accordingly.

In [169]:
def sum_of(x):
    d = 0
    r = 0
    
    for c in x:
        if (c == 'D'):
            d += 1
        else:
            r += 1
    return d, r

In [34]:
"""extract how counties prediction for every state"""
visited = {}
electoral_votes = {'D':0, 'R':0 }
for idnex, row in data_2020.iterrows():
    state = int(row['STATE_FIPS'])
    
    rep_votes = int(row['REP_VOTES'])
    dem_votes = int(row['DEM_VOTES'])

    if (visited.get(state) == None):
        electoral_votes = {'D': dem_votes, 'R': rep_votes }
        visited[state] = electoral_votes
    else:
        #update existing map
        current_votes = visited.get(state)
        current_r = current_votes.get('R')
        current_d = current_votes.get('D')
        electoral_votes = {'D': current_d + dem_votes, 'R': current_r + rep_votes }
        visited[state] = electoral_votes

In [35]:
## new
visited

{1: {'D': 1039171, 'R': 1224317},
 2: {'D': 184110, 'R': 219040},
 4: {'D': 1864573, 'R': 771449},
 5: {'D': 583938, 'R': 747426},
 6: {'D': 10565049, 'R': 3557231},
 8: {'D': 1408934, 'R': 1149515},
 9: {'D': 1039857, 'R': 605609},
 10: {'D': 256508, 'R': 192415},
 11: {'D': 178707, 'R': 100752},
 12: {'D': 5085678, 'R': 3956695},
 13: {'D': 2507337, 'R': 2271003},
 15: {'D': 289646, 'R': 168482},
 16: {'D': 351828, 'R': 503163},
 17: {'D': 3435090, 'R': 2047363},
 18: {'D': 1337891, 'R': 1674333},
 19: {'D': 682636, 'R': 982535},
 20: {'D': 629390, 'R': 854131},
 21: {'D': 981468, 'R': 1181583},
 22: {'D': 922636, 'R': 1068221},
 23: {'D': 338593, 'R': 355285},
 24: {'D': 1550236, 'R': 1115732},
 25: {'D': 2057320, 'R': 1148019},
 26: {'D': 2544019, 'R': 2158323},
 27: {'D': 1429731, 'R': 1270426},
 28: {'D': 612618, 'R': 672803},
 29: {'D': 1257841, 'R': 1561699},
 30: {'D': 229926, 'R': 363270},
 31: {'D': 438473, 'R': 534322},
 32: {'D': 798153, 'R': 436014},
 33: {'D': 364194, 'R': 343053},
 34: {'D': 2287651, 'R': 1524531},
 35: {'D': 397814, 'R': 323212},
 36: {'D': 4858103, 'R': 3257986},
 37: {'D': 2434682, 'R': 2251118},
 38: {'D': 164714, 'R': 263681},
 39: {'D': 2747259, 'R': 2647359},
 40: {'D': 775933, 'R': 736898},
 41: {'D': 1001391, 'R': 866469},
 42: {'D': 3207786, 'R': 2692657},
 44: {'D': 285668, 'R': 206164},
 45: {'D': 1142673, 'R': 1143657},
 46: {'D': 214137, 'R': 337319},
 47: {'D': 1301367, 'R': 1708361},
 48: {'D': 5655112, 'R': 4454931},
 49: {'D': 508485, 'R': 570725},
 50: {'D': 128427, 'R': 181601},
 51: {'D': 1980910, 'R': 1972783},
 53: {'D': 1998890, 'R': 1231938},
 54: {'D': 327525, 'R': 513216},
 55: {'D': 1350093, 'R': 1390204},
 56: {'D': 80019, 'R': 147602}}

In [55]:
"""determine the winner of every state"""
state_predictions = {}
d_count = 0
r_count = 0

for key, val in visited.items():
    total_r = val.get('R')
    total_d = val.get('D')
    winner = 'D' if total_d > total_r else 'R'
    
    if (winner == 'D'):
        d_count +=1 
    elif (winner == 'R'):
        r_count +=1
    
    state_predictions[key] = winner

print('r=' + str(r_count))
print('d=' + str(d_count))

r=23
d=28

In [37]:
##new
state_predictions

{1: 'R',
 2: 'R',
 4: 'D',
 5: 'R',
 6: 'D',
 8: 'D',
 9: 'D',
 10: 'D',
 11: 'D',
 12: 'D',
 13: 'D',
 15: 'D',
 16: 'R',
 17: 'D',
 18: 'R',
 19: 'R',
 20: 'R',
 21: 'R',
 22: 'R',
 23: 'R',
 24: 'D',
 25: 'D',
 26: 'D',
 27: 'D',
 28: 'R',
 29: 'R',
 30: 'R',
 31: 'R',
 32: 'D',
 33: 'D',
 34: 'D',
 35: 'D',
 36: 'D',
 37: 'D',
 38: 'R',
 39: 'D',
 40: 'D',
 41: 'D',
 42: 'D',
 44: 'D',
 45: 'R',
 46: 'R',
 47: 'R',
 48: 'D',
 49: 'R',
 50: 'R',
 51: 'D',
 53: 'D',
 54: 'R',
 55: 'R',
 56: 'R'}

In [39]:
df

                   STATE  COUNT  STATE_FIPS
0                Alabama      9           1
1                 Alaska      3           2
2                Arizona     11           4
3               Arkansas      6           5
4             California     55           6
5               Colorado      9           8
6            Connecticut      7           9
7               Delaware      3          10
8   District of Columbia      3          11
9                Florida     29          12
10               Georgia     16          13
11                Hawaii      4          15
12                 Idaho      4          16
13              Illinois     20          17
14               Indiana     11          18
15                  Iowa      6          19
16                Kansas      6          20
17              Kentucky      8          21
18             Louisiana      8          22
19                 Maine      4          23
20              Maryland     10          24
21         Massachusetts     11          25
22              Michigan     16          26
23             Minnesota     10          27
24           Mississippi      6          28
25              Missouri     10          29
26               Montana      3          30
27              Nebraska      5          31
28                Nevada      6          32
29         New Hampshire      4          33
30            New Jersey     14          34
31            New Mexico      5          35
32              New York     29          36
33        North Carolina     15          37
34          North Dakota      3          38
35                  Ohio     18          39
36              Oklahoma      7          40
37                Oregon      7          41
38          Pennsylvania     20          42
39          Rhode Island      4          44
40        South Carolina      9          45
41          South Dakota      3          46
42             Tennessee     11          47
43                 Texas     38          48
44                  Utah      6          49
45               Vermont      3          50
46              Virginia     13          51
47            Washington     12          53
48         West Virginia      5          54
49             Wisconsin     10          55
50               Wyoming      3          56

In [51]:
party_electoral = {}
for index, row in df.iterrows():
    state = int(row['STATE_FIPS'])
    votes = int(row['COUNT'])
    party = state_predictions.get(state)
    
    if (party_electoral.get(party) == None):
        party_electoral[party] = votes
    else:
        new_total = party_electoral.get(party) + votes
        party_electoral[party] = new_total

In [52]:
party_electoral

{'R': 142, 'D': 396}