In [2]:
import pandas as pd

In [3]:
electoral_ref = pd.read_excel('../../data/Electoral College Votes.xlsx')
data_2020 = pd.read_csv('../../data/F20_phase3_0716.csv')
data_historical = pd.read_csv("../../data/Data-Jul16/combined_jul16.csv", encoding = "ISO-8859-1")

In [4]:
### 1) create a new df with StateFips/Count

In [5]:
state_fips_map = {}
for index, row in data_historical.iterrows():
    #print(row)
    state = row['STATE']
    #print(type(state))
    if (state_fips_map.get(state) == None):
        state_fips_map[state] = row['STATE_FIPS']
    
print(state_fips_map)

{'Alabama': 1, 'Alaska': 2, 'Arizona': 4, 'Arkansas': 5, 'California': 6, 'Colorado': 8, 'Connecticut': 9, 'Delaware': 10, 'District of Columbia': 11, 'Florida': 12, 'Georgia': 13, 'Hawaii': 15, 'Idaho': 16, 'Illinois': 17, 'Indiana': 18, 'Iowa': 19, 'Kansas': 20, 'Kentucky': 21, 'Louisiana': 22, 'Maine': 23, 'Maryland': 24, 'Massachusetts': 25, 'Michigan': 26, 'Minnesota': 27, 'Mississippi': 28, 'Missouri': 29, 'Montana': 30, 'Nebraska': 31, 'Nevada': 32, 'New Hampshire': 33, 'New Jersey': 34, 'New Mexico': 35, 'New York': 36, 'North Carolina': 37, 'North Dakota': 38, 'Ohio': 39, 'Oklahoma': 40, 'Oregon': 41, 'Pennsylvania': 42, 'Rhode Island': 44, 'South Carolina': 45, 'South Dakota': 46, 'Tennessee': 47, 'Texas': 48, 'Utah': 49, 'Vermont': 50, 'Virginia': 51, 'Washington': 53, 'West Virginia': 54, 'Wisconsin': 55, 'Wyoming': 56}

In [6]:
state_fips_df = pd.DataFrame(list(state_fips_map.items()), columns=['STATE','STATE_FIPS'])

In [7]:
state_fips_df.head()

        STATE  STATE_FIPS
0     Alabama           1
1      Alaska           2
2     Arizona           4
3    Arkansas           5
4  California           6

In [8]:
df = electoral_ref.merge(state_fips_df, left_on='STATE', right_on='STATE')

In [9]:
df.head()

        STATE  COUNT  STATE_FIPS
0     Alabama      9           1
1      Alaska      3           2
2     Arizona     11           4
3    Arkansas      6           5
4  California     55           6

In [10]:
data_2020.loc[data_2020['STATE_FIPS'] == 13]

,Unnamed: 0,Unnamed: 0.1,YEAR_FIPS,YEAR,STATE_FIPS,COUNTY_FIPS,HOUSE_WINNING_BINARY,SENATE_WINNING_BINARY,UNEMPLOYMENT_RATE,AVG_WAGE_SALARY,...,TOT_POP_LESS19%,TOT_POP_20to39%,TOT_POP_40to59%,TOT_POP_Above60%,COUNTY_TOTALVOTES,WINNING_PARTY_BINARY,REP_VOTES%,DEM_VOTES%,REP_VOTES,DEM_VOTES
387,387,387,202013001,2020,13,1,0,-1,6.3,34006,...,0.269898,0.238288,0.252067,0.239747,8400,1,0.634381,0.365619,5328,3071
388,388,388,202013003,2020,13,3,0,-1,4.3,0,...,0.286971,0.257684,0.258166,0.197180,2617,1,0.635224,0.364776,1662,954
389,389,389,202013005,2020,13,5,0,-1,5.5,0,...,0.276531,0.246848,0.251140,0.225481,6142,1,0.635004,0.364996,3900,2241
390,390,390,202013007,2020,13,7,0,-1,10.4,0,...,0.211837,0.216041,0.266494,0.305627,4312,0,0.391420,0.608580,1687,2624
391,391,391,202013009,2020,13,9,0,-1,6.6,109924,...,0.250474,0.294626,0.232068,0.222832,23495,1,0.633391,0.366609,14881,8613
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
541,541,541,202013313,2020,13,313,0,-1,7.3,74584,...,0.284773,0.264025,0.257154,0.194048,40061,1,0.659278,0.340722,26411,13649
542,542,542,202013315,2020,13,315,0,-1,5.1,0,...,0.210395,0.286995,0.262823,0.239787,4256,1,0.663545,0.336455,2824,1431
543,543,543,202013317,2020,13,317,0,-1,4.1,0,...,0.233900,0.207270,0.250101,0.308728,8587,1,0.663234,0.336766,5695,2891
544,544,544,202013319,2020,13,319,0,-1,3.1,0,...,0.249668,0.223882,0.252767,0.273683,8097,1,0.663472,0.336528,5372,2724
545,545,545,202013321,2020,13,321,0,-1,3.4,34933,...,0.244692,0.232819,0.261885,0.260604,13914,1,0.662992,0.337008,9224,4689

In [11]:
data_2020.drop('Unnamed: 0', inplace=True, axis=1)

In [12]:
## 2) 

# create map of visited county_state
# create map of D electoral votes, R electoral votes
# loop over data_2020
# updaste the two maps accordingly.

In [13]:
def sum_of(x):
    d = 0
    r = 0
    
    for c in x:
        if (c == 'D'):
            d += 1
        else:
            r += 1
    return d, r

In [14]:
"""extract how counties prediction for every state"""
visited = {}
electoral_votes = {'D':0, 'R':0 }
for idnex, row in data_2020.iterrows():
    state = int(row['STATE_FIPS'])
    
    rep_votes = int(row['REP_VOTES'])
    dem_votes = int(row['DEM_VOTES'])

    if (visited.get(state) == None):
        electoral_votes = {'D': dem_votes, 'R': rep_votes }
        visited[state] = electoral_votes
    else:
        #update existing map
        current_votes = visited.get(state)
        current_r = current_votes.get('R')
        current_d = current_votes.get('D')
        electoral_votes = {'D': current_d + dem_votes, 'R': current_r + rep_votes }
        visited[state] = electoral_votes

In [16]:
## new
visited

{1: {'D': 1038767, 'R': 1224721},
 2: {'D': 191020, 'R': 212130},
 4: {'D': 1414943, 'R': 1221079},
 5: {'D': 548082, 'R': 783282},
 6: {'D': 10384613, 'R': 3737667},
 8: {'D': 1499372, 'R': 1059077},
 9: {'D': 1063383, 'R': 582083},
 10: {'D': 257379, 'R': 191544},
 11: {'D': 179189, 'R': 100270},
 12: {'D': 4670764, 'R': 4371609},
 13: {'D': 2452061, 'R': 2326279},
 15: {'D': 290475, 'R': 167653},
 16: {'D': 370883, 'R': 484108},
 17: {'D': 3393540, 'R': 2088913},
 18: {'D': 1258578, 'R': 1753646},
 19: {'D': 724684, 'R': 940487},
 20: {'D': 639573, 'R': 843948},
 21: {'D': 901325, 'R': 1261726},
 22: {'D': 864061, 'R': 1126796},
 23: {'D': 333028, 'R': 360850},
 24: {'D': 1531517, 'R': 1134451},
 25: {'D': 2064969, 'R': 1140370},
 26: {'D': 2438719, 'R': 2263623},
 27: {'D': 1284740, 'R': 1415417},
 28: {'D': 553927, 'R': 731494},
 29: {'D': 1291269, 'R': 1528271},
 30: {'D': 230760, 'R': 362436},
 31: {'D': 352192, 'R': 620603},
 32: {'D': 790209, 'R': 443958},
 33: {'D': 336869, 'R': 370378},
 34: {'D': 2296835, 'R': 1515347},
 35: {'D': 378879, 'R': 342147},
 36: {'D': 4706658, 'R': 3409431},
 37: {'D': 2371966, 'R': 2313834},
 38: {'D': 156356, 'R': 272039},
 39: {'D': 2584604, 'R': 2810014},
 40: {'D': 650682, 'R': 862149},
 41: {'D': 1038159, 'R': 829701},
 42: {'D': 2933814, 'R': 2966629},
 44: {'D': 297222, 'R': 194610},
 45: {'D': 1022695, 'R': 1263635},
 46: {'D': 208889, 'R': 342567},
 47: {'D': 1350641, 'R': 1659087},
 48: {'D': 5343487, 'R': 4766556},
 49: {'D': 498119, 'R': 581091},
 50: {'D': 160714, 'R': 149314},
 51: {'D': 1900717, 'R': 2052976},
 53: {'D': 1884730, 'R': 1346098},
 54: {'D': 303317, 'R': 537424},
 55: {'D': 1206888, 'R': 1533409},
 56: {'D': 79648, 'R': 147973}}

In [17]:
"""determine the winner of every state"""
state_predictions = {}
d_count = 0
r_count = 0

for key, val in visited.items():
    total_r = val.get('R')
    total_d = val.get('D')
    winner = 'D' if total_d > total_r else 'R'
    
    if (winner == 'D'):
        d_count +=1 
    elif (winner == 'R'):
        r_count +=1
    
    state_predictions[key] = winner

print('r=' + str(r_count))
print('d=' + str(d_count))

r=28
d=23

In [18]:
##new
state_predictions

{1: 'R',
 2: 'R',
 4: 'D',
 5: 'R',
 6: 'D',
 8: 'D',
 9: 'D',
 10: 'D',
 11: 'D',
 12: 'D',
 13: 'D',
 15: 'D',
 16: 'R',
 17: 'D',
 18: 'R',
 19: 'R',
 20: 'R',
 21: 'R',
 22: 'R',
 23: 'R',
 24: 'D',
 25: 'D',
 26: 'D',
 27: 'R',
 28: 'R',
 29: 'R',
 30: 'R',
 31: 'R',
 32: 'D',
 33: 'R',
 34: 'D',
 35: 'D',
 36: 'D',
 37: 'D',
 38: 'R',
 39: 'R',
 40: 'R',
 41: 'D',
 42: 'R',
 44: 'D',
 45: 'R',
 46: 'R',
 47: 'R',
 48: 'D',
 49: 'R',
 50: 'D',
 51: 'R',
 53: 'D',
 54: 'R',
 55: 'R',
 56: 'R'}

In [19]:
df

                   STATE  COUNT  STATE_FIPS
0                Alabama      9           1
1                 Alaska      3           2
2                Arizona     11           4
3               Arkansas      6           5
4             California     55           6
5               Colorado      9           8
6            Connecticut      7           9
7               Delaware      3          10
8   District of Columbia      3          11
9                Florida     29          12
10               Georgia     16          13
11                Hawaii      4          15
12                 Idaho      4          16
13              Illinois     20          17
14               Indiana     11          18
15                  Iowa      6          19
16                Kansas      6          20
17              Kentucky      8          21
18             Louisiana      8          22
19                 Maine      4          23
20              Maryland     10          24
21         Massachusetts     11          25
22              Michigan     16          26
23             Minnesota     10          27
24           Mississippi      6          28
25              Missouri     10          29
26               Montana      3          30
27              Nebraska      5          31
28                Nevada      6          32
29         New Hampshire      4          33
30            New Jersey     14          34
31            New Mexico      5          35
32              New York     29          36
33        North Carolina     15          37
34          North Dakota      3          38
35                  Ohio     18          39
36              Oklahoma      7          40
37                Oregon      7          41
38          Pennsylvania     20          42
39          Rhode Island      4          44
40        South Carolina      9          45
41          South Dakota      3          46
42             Tennessee     11          47
43                 Texas     38          48
44                  Utah      6          49
45               Vermont      3          50
46              Virginia     13          51
47            Washington     12          53
48         West Virginia      5          54
49             Wisconsin     10          55
50               Wyoming      3          56

In [20]:
party_electoral = {}
for index, row in df.iterrows():
    state = int(row['STATE_FIPS'])
    votes = int(row['COUNT'])
    party = state_predictions.get(state)
    
    if (party_electoral.get(party) == None):
        party_electoral[party] = votes
    else:
        new_total = party_electoral.get(party) + votes
        party_electoral[party] = new_total

In [52]:
party_electoral

{'R': 142, 'D': 396}

In [21]:
party_electoral

{'R': 211, 'D': 327}