In [2]:
import pandas as pd

In [3]:
electoral_ref = pd.read_excel('../../data/Electoral College Votes.xlsx')
data_2020 = pd.read_csv('../../data/F20_phase3_0717_target.csv')
data_historical = pd.read_csv("../../data/Data-Jul16/combined_jul16.csv", encoding = "ISO-8859-1")

In [4]:
### 1) create a new df with StateFips/Count

In [5]:
state_fips_map = {}
for index, row in data_historical.iterrows():
    #print(row)
    state = row['STATE']
    #print(type(state))
    if (state_fips_map.get(state) == None):
        state_fips_map[state] = row['STATE_FIPS']
    
print(state_fips_map)

{'Alabama': 1, 'Alaska': 2, 'Arizona': 4, 'Arkansas': 5, 'California': 6, 'Colorado': 8, 'Connecticut': 9, 'Delaware': 10, 'District of Columbia': 11, 'Florida': 12, 'Georgia': 13, 'Hawaii': 15, 'Idaho': 16, 'Illinois': 17, 'Indiana': 18, 'Iowa': 19, 'Kansas': 20, 'Kentucky': 21, 'Louisiana': 22, 'Maine': 23, 'Maryland': 24, 'Massachusetts': 25, 'Michigan': 26, 'Minnesota': 27, 'Mississippi': 28, 'Missouri': 29, 'Montana': 30, 'Nebraska': 31, 'Nevada': 32, 'New Hampshire': 33, 'New Jersey': 34, 'New Mexico': 35, 'New York': 36, 'North Carolina': 37, 'North Dakota': 38, 'Ohio': 39, 'Oklahoma': 40, 'Oregon': 41, 'Pennsylvania': 42, 'Rhode Island': 44, 'South Carolina': 45, 'South Dakota': 46, 'Tennessee': 47, 'Texas': 48, 'Utah': 49, 'Vermont': 50, 'Virginia': 51, 'Washington': 53, 'West Virginia': 54, 'Wisconsin': 55, 'Wyoming': 56}

In [6]:
state_fips_df = pd.DataFrame(list(state_fips_map.items()), columns=['STATE','STATE_FIPS'])

In [7]:
state_fips_df

                   STATE  STATE_FIPS
0                Alabama           1
1                 Alaska           2
2                Arizona           4
3               Arkansas           5
4             California           6
5               Colorado           8
6            Connecticut           9
7               Delaware          10
8   District of Columbia          11
9                Florida          12
10               Georgia          13
11                Hawaii          15
12                 Idaho          16
13              Illinois          17
14               Indiana          18
15                  Iowa          19
16                Kansas          20
17              Kentucky          21
18             Louisiana          22
19                 Maine          23
20              Maryland          24
21         Massachusetts          25
22              Michigan          26
23             Minnesota          27
24           Mississippi          28
25              Missouri          29
26               Montana          30
27              Nebraska          31
28                Nevada          32
29         New Hampshire          33
30            New Jersey          34
31            New Mexico          35
32              New York          36
33        North Carolina          37
34          North Dakota          38
35                  Ohio          39
36              Oklahoma          40
37                Oregon          41
38          Pennsylvania          42
39          Rhode Island          44
40        South Carolina          45
41          South Dakota          46
42             Tennessee          47
43                 Texas          48
44                  Utah          49
45               Vermont          50
46              Virginia          51
47            Washington          53
48         West Virginia          54
49             Wisconsin          55
50               Wyoming          56

In [29]:
df = electoral_ref.merge(state_fips_df, left_on='STATE', right_on='STATE')

In [1]:
df

NameError: name 'df' is not defined

In [31]:
data_2020.loc[data_2020['STATE_FIPS'] == 13]

,Unnamed: 0,Unnamed: 0.1,YEAR_FIPS,STATE_FIPS,COUNTY_FIPS,HOUSE_WINNING_BINARY,SENATE_WINNING_BINARY,UNEMPLOYMENT_RATE,AVG_WAGE_SALARY,AA_FEMALE,...,TOT_POP_LESS19%,TOT_POP_20to39%,TOT_POP_40to59%,TOT_POP_Above60%,COUNTY_TOTALVOTES,WINNING_PARTY_BINARY,REP_VOTES%,DEM_VOTES%,REP_VOTES,DEM_VOTES
390,390,3535,201613001,13,1,0,1,6.4,43357,63,...,0.274789,0.238417,0.267374,0.219420,5046,1,0.626205,0.373795,3159,1886
391,391,3536,201613003,13,3,0,1,5.2,34466,29,...,0.303115,0.255902,0.262959,0.178024,-2405,1,0.627105,0.372895,-1508,-896
392,392,3537,201613005,13,5,0,1,5.2,34772,33,...,0.281163,0.256197,0.256018,0.206622,3709,1,0.626638,0.373362,2324,1384
393,393,3538,201613007,13,7,0,1,7.7,0,17,...,0.224484,0.215371,0.287667,0.272479,3328,0,0.396323,0.603677,1318,2009
394,394,3539,201613009,13,9,0,1,6.8,0,357,...,0.258069,0.298362,0.243673,0.199895,21095,0,0.394681,0.605319,8325,12769
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
544,544,3689,201613313,13,313,0,1,6.1,44383,837,...,0.296605,0.265336,0.261662,0.176396,37248,1,0.646242,0.353758,24071,13176
545,545,3690,201613315,13,315,0,1,7.2,0,20,...,0.208413,0.287707,0.280621,0.223259,3064,1,0.649838,0.350162,1991,1072
546,546,3691,201613317,13,317,0,1,6.6,66216,37,...,0.238086,0.203700,0.275890,0.282325,6189,1,0.649673,0.350327,4020,2168
547,547,3692,201613319,13,319,0,1,6.3,92628,26,...,0.253743,0.224233,0.281099,0.240926,5254,1,0.649916,0.350084,3414,1839
548,548,3693,201613321,13,321,0,1,5.8,101256,78,...,0.253794,0.234860,0.274916,0.236430,11213,1,0.649464,0.350536,7282,3930

In [32]:
data_2020.drop('Unnamed: 0', inplace=True, axis=1)

In [33]:
## 2) 

# create map of visited county_state
# create map of D electoral votes, R electoral votes
# loop over data_2020
# updaste the two maps accordingly.

In [34]:
def sum_of(x):
    d = 0
    r = 0
    
    for c in x:
        if (c == 'D'):
            d += 1
        else:
            r += 1
    return d, r

In [35]:
"""extract how counties prediction for every state"""
visited = {}
electoral_votes = {'D':0, 'R':0 }
for idnex, row in data_2020.iterrows():
    state = int(row['STATE_FIPS'])
    
    rep_votes = int(row['REP_VOTES'])
    dem_votes = int(row['DEM_VOTES'])

    if (visited.get(state) == None):
        electoral_votes = {'D': dem_votes, 'R': rep_votes }
        visited[state] = electoral_votes
    else:
        #update existing map
        current_votes = visited.get(state)
        current_r = current_votes.get('R')
        current_d = current_votes.get('D')
        electoral_votes = {'D': current_d + dem_votes, 'R': current_r + rep_votes }
        visited[state] = electoral_votes

In [36]:
## new
visited

{1: {'D': 972982, 'R': 1140260},
 2: {'D': 208859, 'R': 288046},
 4: {'D': 1568931, 'R': 779348},
 5: {'D': 501675, 'R': 689892},
 6: {'D': 9872079, 'R': 3925142},
 8: {'D': 1211779, 'R': 1046474},
 9: {'D': 1051064, 'R': 629593},
 10: {'D': 244676, 'R': 182415},
 11: {'D': 172823, 'R': 100594},
 12: {'D': 4502061, 'R': 3713329},
 13: {'D': 2160257, 'R': 2089227},
 15: {'D': 270784, 'R': 161530},
 16: {'D': 320243, 'R': 373825},
 17: {'D': 3328641, 'R': 2088177},
 18: {'D': 1339699, 'R': 1580702},
 19: {'D': 643395, 'R': 796780},
 20: {'D': 556851, 'R': 715110},
 21: {'D': 834165, 'R': 1086681},
 22: {'D': 832491, 'R': 1017641},
 23: {'D': 374682, 'R': 292853},
 24: {'D': 1554221, 'R': 1143283},
 25: {'D': 1997506, 'R': 1203276},
 26: {'D': 2508800, 'R': 2095627},
 27: {'D': 1329813, 'R': 1231219},
 28: {'D': 508073, 'R': 641286},
 29: {'D': 1261185, 'R': 1433031},
 30: {'D': 197258, 'R': 329578},
 31: {'D': 378997, 'R': 505301},
 32: {'D': 699350, 'R': 428023},
 33: {'D': 386175, 'R': 320011},
 34: {'D': 2135376, 'R': 1751813},
 35: {'D': 357811, 'R': 327060},
 36: {'D': 4847360, 'R': 3326181},
 37: {'D': 2106324, 'R': 2189339},
 38: {'D': 170345, 'R': 241680},
 39: {'D': 2672584, 'R': 2648855},
 40: {'D': 612843, 'R': 787526},
 41: {'D': 947149, 'R': 779487},
 42: {'D': 3107108, 'R': 2820626},
 44: {'D': 296986, 'R': 205214},
 45: {'D': 899052, 'R': 1159528},
 46: {'D': 182884, 'R': 278489},
 47: {'D': 1195534, 'R': 1644647},
 48: {'D': 4754373, 'R': 4626020},
 49: {'D': 343896, 'R': 569640},
 50: {'D': 173203, 'R': 128332},
 51: {'D': 1809332, 'R': 2021888},
 53: {'D': 1810315, 'R': 1258348},
 54: {'D': 330167, 'R': 497356},
 55: {'D': 1257726, 'R': 1404664},
 56: {'D': 80646, 'R': 146084}}

In [37]:
"""determine the winner of every state"""
state_predictions = {}
d_count = 0
r_count = 0

for key, val in visited.items():
    total_r = val.get('R')
    total_d = val.get('D')
    winner = 'D' if total_d > total_r else 'R'
    
    if (winner == 'D'):
        d_count +=1 
    elif (winner == 'R'):
        r_count +=1
    
    state_predictions[key] = winner

In [38]:
print('r=' + str(r_count))
print('d=' + str(d_count))

r=24
d=27

In [39]:
##new
state_predictions

{1: 'R',
 2: 'R',
 4: 'D',
 5: 'R',
 6: 'D',
 8: 'D',
 9: 'D',
 10: 'D',
 11: 'D',
 12: 'D',
 13: 'D',
 15: 'D',
 16: 'R',
 17: 'D',
 18: 'R',
 19: 'R',
 20: 'R',
 21: 'R',
 22: 'R',
 23: 'D',
 24: 'D',
 25: 'D',
 26: 'D',
 27: 'D',
 28: 'R',
 29: 'R',
 30: 'R',
 31: 'R',
 32: 'D',
 33: 'D',
 34: 'D',
 35: 'D',
 36: 'D',
 37: 'R',
 38: 'R',
 39: 'D',
 40: 'R',
 41: 'D',
 42: 'D',
 44: 'D',
 45: 'R',
 46: 'R',
 47: 'R',
 48: 'D',
 49: 'R',
 50: 'D',
 51: 'R',
 53: 'D',
 54: 'R',
 55: 'R',
 56: 'R'}

In [40]:
df

                   STATE  COUNT  STATE_FIPS
0                Alabama      9           1
1                 Alaska      3           2
2                Arizona     11           4
3               Arkansas      6           5
4             California     55           6
5               Colorado      9           8
6            Connecticut      7           9
7               Delaware      3          10
8   District of Columbia      3          11
9                Florida     29          12
10               Georgia     16          13
11                Hawaii      4          15
12                 Idaho      4          16
13              Illinois     20          17
14               Indiana     11          18
15                  Iowa      6          19
16                Kansas      6          20
17              Kentucky      8          21
18             Louisiana      8          22
19                 Maine      4          23
20              Maryland     10          24
21         Massachusetts     11          25
22              Michigan     16          26
23             Minnesota     10          27
24           Mississippi      6          28
25              Missouri     10          29
26               Montana      3          30
27              Nebraska      5          31
28                Nevada      6          32
29         New Hampshire      4          33
30            New Jersey     14          34
31            New Mexico      5          35
32              New York     29          36
33        North Carolina     15          37
34          North Dakota      3          38
35                  Ohio     18          39
36              Oklahoma      7          40
37                Oregon      7          41
38          Pennsylvania     20          42
39          Rhode Island      4          44
40        South Carolina      9          45
41          South Dakota      3          46
42             Tennessee     11          47
43                 Texas     38          48
44                  Utah      6          49
45               Vermont      3          50
46              Virginia     13          51
47            Washington     12          53
48         West Virginia      5          54
49             Wisconsin     10          55
50               Wyoming      3          56

In [41]:
party_electoral = {}
for index, row in df.iterrows():
    state = int(row['STATE_FIPS'])
    votes = int(row['COUNT'])
    party = state_predictions.get(state)
    
    if (party_electoral.get(party) == None):
        party_electoral[party] = votes
    else:
        new_total = party_electoral.get(party) + votes
        party_electoral[party] = new_total

In [42]:
party_electoral

{'R': 170, 'D': 368}

In [21]:
party_electoral

{'R': 211, 'D': 327}