In [5]:
import pandas as pd
import numpy as np
import os

In [6]:
#pop = pd.read_csv('popcon_ex_perc.csv')
pop_total = pd.read_csv('https://raw.githubusercontent.com/ehuang13/w210-presidential-election/master/ellie/popcon_Total.csv')
election = pd.read_csv('https://raw.githubusercontent.com/ehuang13/w210-presidential-election/master/merged_dataset_ellie.csv')

In [7]:
pop_total.head()

,ID,SUMLEV,STATE,COUNTY,FIPS,STNAME,CTYNAME,AGEGRP,Year,TOT_POP,...,BA_MALE,BA_FEMALE,IA_MALE,IA_FEMALE,AA_MALE,AA_FEMALE,NA_MALE,NA_FEMALE,H_MALE,H_FEMALE
0,20201001,50,1,1,1001,Alabama,Autauga County,Total,2020,55601,...,5153,5762,121,146,301,380,33,29,860,789
1,20201003,50,1,3,1003,Alabama,Baldwin County,Total,2020,218022,...,9400,10092,886,798,933,1575,73,73,5302,4829
2,20201005,50,1,5,1005,Alabama,Barbour County,Total,2020,24881,...,6370,5672,97,67,52,61,30,16,584,480
3,20201007,50,1,7,1007,Alabama,Bibb County,Total,2020,22400,...,2954,1816,48,50,19,34,22,4,335,253
4,20201009,50,1,9,1009,Alabama,Blount County,Total,2020,57840,...,507,443,195,183,82,103,44,26,2939,2597

In [8]:
dataTypeObj = pop_total.dtypes['ID']
 
print('Data type of each column ID in the Dataframe :')
print(dataTypeObj)

Data type of each column ID in the Dataframe :
int64

In [9]:
pop_total["ID"] = pop_total["ID"].astype(str)

In [10]:
for col in election.columns: 
    print(col)

year
state
state_po
county
fips
fips_trimmed
republican_candidate
democrat_candidate
republican_votes
democrat_votes
county_totalvotes
winning candidate
winning party
avg_wage_salary

In [11]:
election.tail()

,year,state,state_po,county,fips,fips_trimmed,republican_candidate,democrat_candidate,republican_votes,democrat_votes,county_totalvotes,winning candidate,winning party,avg_wage_salary
15784,2016,Alaska,AK,District 37,2037.0,2037.0,Donald Trump,Hillary Clinton,1938,2421,5062.0,Hillary Clinton,democrat,0
15785,2016,Alaska,AK,District 38,2038.0,2038.0,Donald Trump,Hillary Clinton,1143,2758,5095.0,Hillary Clinton,democrat,0
15786,2016,Alaska,AK,District 39,2039.0,2039.0,Donald Trump,Hillary Clinton,1405,3142,5639.0,Hillary Clinton,democrat,0
15787,2016,Alaska,AK,District 40,2040.0,2040.0,Donald Trump,Hillary Clinton,1377,2338,4610.0,Hillary Clinton,democrat,0
15788,2016,Alaska,NaN,District 99,2099.0,2099.0,Donald Trump,Hillary Clinton,40,274,5056.0,Hillary Clinton,democrat,0

In [23]:
# EH added to create ID column from year + fips
election['ID'] = election['year'].map(str) + election['fips'].map(str)

In [24]:
election.head()

,year,state,state_po,county,fips,fips_trimmed,republican_candidate,democrat_candidate,republican_votes,democrat_votes,county_totalvotes,winning candidate,winning party,avg_wage_salary,ID
0,2000,Alaska,AK,District 1,2001.0,2001.0,George W. Bush,Al Gore,4681,1284,6656.0,George W. Bush,republican,0,20002001.0
1,2000,Alaska,AK,District 2,2002.0,2002.0,George W. Bush,Al Gore,4235,2081,7388.0,George W. Bush,republican,0,20002002.0
2,2000,Alaska,AK,District 3,2003.0,2003.0,George W. Bush,Al Gore,3135,3693,8225.0,Al Gore,democrat,0,20002003.0
3,2000,Alaska,AK,District 4,2004.0,2004.0,George W. Bush,Al Gore,4127,2715,7823.0,George W. Bush,republican,0,20002004.0
4,2000,Alaska,AK,District 5,2005.0,2005.0,George W. Bush,Al Gore,3545,1931,6437.0,George W. Bush,republican,0,20002005.0

In [25]:
dataTypeObj = election.dtypes['ID']
 
print('Data type of each column ID in the Dataframe :')
print(dataTypeObj)

Data type of each column ID in the Dataframe :
object

In [26]:
election["ID"] = election["ID"].astype(str)

In [27]:
data = pd.merge(pop_total,election, on='ID', how='left')
data.tail()

,ID,SUMLEV,STATE,COUNTY,FIPS,STNAME,CTYNAME,AGEGRP,Year,TOT_POP,...,fips,fips_trimmed,republican_candidate,democrat_candidate,republican_votes,democrat_votes,county_totalvotes,winning candidate,winning party,avg_wage_salary
9421,201256037,50,56,37,56037,Wyoming,Sweetwater County,Total,2012,43574,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9422,201256039,50,56,39,56039,Wyoming,Teton County,Total,2012,21297,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9423,201256041,50,56,41,56041,Wyoming,Uinta County,Total,2012,21089,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9424,201256043,50,56,43,56043,Wyoming,Washakie County,Total,2012,8530,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9425,201256045,50,56,45,56045,Wyoming,Weston County,Total,2012,7199,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
for col in data.columns: 
    print(col)

ID
SUMLEV
STATE
COUNTY
FIPS
STNAME
CTYNAME
AGEGRP
Year
TOT_POP
TOT_MALE
TOT_FEMALE
WA_MALE
WA_FEMALE
BA_MALE
BA_FEMALE
IA_MALE
IA_FEMALE
AA_MALE
AA_FEMALE
NA_MALE
NA_FEMALE
H_MALE
H_FEMALE
year
state
state_po
county
fips
fips_trimmed
republican_candidate
democrat_candidate
republican_votes
democrat_votes
county_totalvotes
winning candidate
winning party
avg_wage_salary

In [29]:
data.drop(['year','state','state_po','county'],axis=1)

,ID,SUMLEV,STATE,COUNTY,FIPS,STNAME,CTYNAME,AGEGRP,Year,TOT_POP,...,fips,fips_trimmed,republican_candidate,democrat_candidate,republican_votes,democrat_votes,county_totalvotes,winning candidate,winning party,avg_wage_salary
0,20201001,50,1,1,1001,Alabama,Autauga County,Total,2020,55601,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20201003,50,1,3,1003,Alabama,Baldwin County,Total,2020,218022,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20201005,50,1,5,1005,Alabama,Barbour County,Total,2020,24881,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20201007,50,1,7,1007,Alabama,Bibb County,Total,2020,22400,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20201009,50,1,9,1009,Alabama,Blount County,Total,2020,57840,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,20201011,50,1,11,1011,Alabama,Bullock County,Total,2020,10138,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,20201013,50,1,13,1013,Alabama,Butler County,Total,2020,19680,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,20201015,50,1,15,1015,Alabama,Calhoun County,Total,2020,114277,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,20201017,50,1,17,1017,Alabama,Chambers County,Total,2020,33615,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,20201019,50,1,19,1019,Alabama,Cherokee County,Total,2020,26032,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,20201021,50,1,21,1021,Alabama,Chilton County,Total,2020,44153,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,20201023,50,1,23,1023,Alabama,Choctaw County,Total,2020,12841,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,20201025,50,1,25,1025,Alabama,Clarke County,Total,2020,23920,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,20201027,50,1,27,1027,Alabama,Clay County,Total,2020,13275,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,20201029,50,1,29,1029,Alabama,Cleburne County,Total,2020,14987,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,20201031,50,1,31,1031,Alabama,Coffee County,Total,2020,51909,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,20201033,50,1,33,1033,Alabama,Colbert County,Total,2020,54762,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,20201035,50,1,35,1035,Alabama,Conecuh County,Total,2020,12277,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,20201037,50,1,37,1037,Alabama,Coosa County,Total,2020,10715,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,20201039,50,1,39,1039,Alabama,Covington County,Total,2020,36986,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,20201041,50,1,41,1041,Alabama,Crenshaw County,Total,2020,13824,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,20201043,50,1,43,1043,Alabama,Cullman County,Total,2020,83442,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,20201045,50,1,45,1045,Alabama,Dale County,Total,2020,48956,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,20201047,50,1,47,1047,Alabama,Dallas County,Total,2020,38310,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,20201049,50,1,49,1049,Alabama,DeKalb County,Total,2020,71385,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,20201051,50,1,51,1051,Alabama,Elmore County,Total,2020,81887,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,20201053,50,1,53,1053,Alabama,Escambia County,Total,2020,36748,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,20201055,50,1,55,1055,Alabama,Etowah County,Total,2020,102501,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,20201057,50,1,57,1057,Alabama,Fayette County,Total,2020,16433,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,20201059,50,1,59,1059,Alabama,Franklin County,Total,2020,31363,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9396,201255129,50,55,129,55129,Wisconsin,Washburn County,Total,2012,15932,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9397,201255131,50,55,131,55131,Wisconsin,Washington County,Total,2012,131987,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9398,201255133,50,55,133,55133,Wisconsin,Waukesha County,Total,2012,390020,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9399,201255135,50,55,135,55135,Wisconsin,Waupaca County,Total,2012,52397,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9400,201255137,50,55,137,55137,Wisconsin,Waushara County,Total,2012,24514,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9401,201255139,50,55,139,55139,Wisconsin,Winnebago County,Total,2012,167069,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9402,201255141,50,55,141,55141,Wisconsin,Wood County,Total,2012,74814,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9403,201256001,50,56,1,56001,Wyoming,Albany County,Total,2012,36465,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9404,201256003,50,56,3,56003,Wyoming,Big Horn County,Total,2012,11666,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9405,201256005,50,56,5,56005,Wyoming,Campbell County,Total,2012,46245,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9406,201256007,50,56,7,56007,Wyoming,Carbon County,Total,2012,15848,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9407,201256009,50,56,9,56009,Wyoming,Converse County,Total,2012,13823,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9408,201256011,50,56,11,56011,Wyoming,Crook County,Total,2012,7121,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9409,201256013,50,56,13,56013,Wyoming,Fremont County,Total,2012,40200,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9410,201256015,50,56,15,56015,Wyoming,Goshen County,Total,2012,13422,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9411,201256017,50,56,17,56017,Wyoming,Hot Springs County,Total,2012,4811,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9412,201256019,50,56,19,56019,Wyoming,Johnson County,Total,2012,8590,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9413,201256021,50,56,21,56021,Wyoming,Laramie County,Total,2012,92235,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9414,201256023,50,56,23,56023,Wyoming,Lincoln County,Total,2012,18098,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9415,201256025,50,56,25,56025,Wyoming,Natrona County,Total,2012,75469,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9416,201256027,50,56,27,56027,Wyoming,Niobrara County,Total,2012,2491,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9417,201256029,50,56,29,56029,Wyoming,Park County,Total,2012,28240,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9418,201256031,50,56,31,56031,Wyoming,Platte County,Total,2012,8665,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9419,201256033,50,56,33,56033,Wyoming,Sheridan County,Total,2012,29144,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9420,201256035,50,56,35,56035,Wyoming,Sublette County,Total,2012,10261,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9421,201256037,50,56,37,56037,Wyoming,Sweetwater County,Total,2012,43574,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9422,201256039,50,56,39,56039,Wyoming,Teton County,Total,2012,21297,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9423,201256041,50,56,41,56041,Wyoming,Uinta County,Total,2012,21089,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9424,201256043,50,56,43,56043,Wyoming,Washakie County,Total,2012,8530,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9425,201256045,50,56,45,56045,Wyoming,Weston County,Total,2012,7199,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
data.head()

,ID,SUMLEV,STATE,COUNTY,FIPS,STNAME,CTYNAME,AGEGRP,Year,TOT_POP,...,fips,fips_trimmed,republican_candidate,democrat_candidate,republican_votes,democrat_votes,county_totalvotes,winning candidate,winning party,avg_wage_salary
0,20201001,50,1,1,1001,Alabama,Autauga County,Total,2020,55601,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20201003,50,1,3,1003,Alabama,Baldwin County,Total,2020,218022,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20201005,50,1,5,1005,Alabama,Barbour County,Total,2020,24881,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20201007,50,1,7,1007,Alabama,Bibb County,Total,2020,22400,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20201009,50,1,9,1009,Alabama,Blount County,Total,2020,57840,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
# updated pop df to data df
pop_agegroup = data.groupby(['ID', 'AGEGRP','FIPS','Year','STATE','COUNTY','STNAME','CTYNAME']).sum().drop(['SUMLEV'], axis=1)

In [32]:
pop_agegroup.head(10)

,,,,,,,,TOT_POP,TOT_MALE,TOT_FEMALE,WA_MALE,WA_FEMALE,BA_MALE,BA_FEMALE,IA_MALE,IA_FEMALE,AA_MALE,...,NA_FEMALE,H_MALE,H_FEMALE,year,fips,fips_trimmed,republican_votes,democrat_votes,county_totalvotes,avg_wage_salary
ID,AGEGRP,FIPS,Year,STATE,COUNTY,STNAME,CTYNAME,,,,,,,,,,,,,,,,,,,,,
201210001,Total,10001,2012,10,1,Delaware,Kent County,162955,78364,84591,55190,57911,18762,21286,561,587,1399,...,75,4627,4806,0.0,0.0,0.0,0.0,0.0,0.0,0.0
201210003,Total,10003,2012,10,3,Delaware,New Castle County,538750,260725,278025,180631,189339,61796,69367,1071,1104,11844,...,150,24309,22903,0.0,0.0,0.0,0.0,0.0,0.0,0.0
201210005,Total,10005,2012,10,5,Delaware,Sussex County,197890,96563,101327,79701,83621,12528,13285,1401,1199,979,...,121,9204,7890,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20121001,Total,1001,2012,1,1,Alabama,Autauga County,54754,26670,28084,21357,22052,4591,5152,119,131,201,...,17,693,615,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20121003,Total,1003,2012,1,3,Alabama,Baldwin County,183111,89618,93493,78718,81752,8421,8913,660,670,551,...,55,4450,3614,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20121005,Total,1005,2012,1,5,Alabama,Barbour County,27330,14504,12826,7414,6482,6786,6111,88,73,59,...,17,747,599,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20121007,Total,1007,2012,1,7,Alabama,Bibb County,22872,12264,10608,9034,8491,3069,1972,36,32,12,...,5,300,110,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20121009,Total,1009,2012,1,9,Alabama,Blount County,57373,28385,28988,27415,27995,424,390,177,173,48,...,25,2582,2081,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20121011,Total,1011,2012,1,11,Alabama,Bullock County,10878,5882,4996,1755,1113,3983,3750,36,49,10,...,36,431,346,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20121013,Total,1013,2012,1,13,Alabama,Butler County,20942,9844,11098,5484,5935,4159,4966,27,35,98,...,5,108,89,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [40]:
pop_agegroup.reset_index()
for col in pop_agegroup.columns: 
    print(col)

TOT_POP
TOT_MALE
TOT_FEMALE
WA_MALE
WA_FEMALE
BA_MALE
BA_FEMALE
IA_MALE
IA_FEMALE
AA_MALE
AA_FEMALE
NA_MALE
NA_FEMALE
H_MALE
H_FEMALE
year
fips
fips_trimmed
republican_votes
democrat_votes
county_totalvotes
avg_wage_salary

In [ ]:
pop_agegroup.to_csv('pop_agegroup.csv')

In [ ]:
pop_total = [pop_agegroup.AGEGRP != '20 to 39']
pop_total = [pop_agegroup.AGEGRP != '40 to 59']
pop_total = [pop_agegroup.AGEGRP != 'Above 60']
pop_total = [pop_agegroup.AGEGRP != 'Less than 19']

### EH code below

In [42]:
# confirm that columns used in groupby were not included in columns
pop_agegroup.columns

Index(['TOT_POP', 'TOT_MALE', 'TOT_FEMALE', 'WA_MALE', 'WA_FEMALE', 'BA_MALE',
       'BA_FEMALE', 'IA_MALE', 'IA_FEMALE', 'AA_MALE', 'AA_FEMALE', 'NA_MALE',
       'NA_FEMALE', 'H_MALE', 'H_FEMALE', 'year', 'fips', 'fips_trimmed',
       'republican_votes', 'democrat_votes', 'county_totalvotes',
       'avg_wage_salary'],
      dtype='object')

In [60]:
# EH aggregation attempt
eh_pop_df = data.groupby(['ID', 'AGEGRP','FIPS','Year','STATE','COUNTY','STNAME','CTYNAME'], as_index = False).agg(lambda x: sum(x))

In [62]:
# confirm columns are retained even when used in groupby
eh_pop_df.columns

Index(['ID', 'AGEGRP', 'FIPS', 'Year', 'STATE', 'COUNTY', 'STNAME', 'CTYNAME',
       'SUMLEV', 'TOT_POP', 'TOT_MALE', 'TOT_FEMALE', 'WA_MALE', 'WA_FEMALE',
       'BA_MALE', 'BA_FEMALE', 'IA_MALE', 'IA_FEMALE', 'AA_MALE', 'AA_FEMALE',
       'NA_MALE', 'NA_FEMALE', 'H_MALE', 'H_FEMALE', 'year', 'state',
       'state_po', 'county', 'fips', 'fips_trimmed', 'republican_candidate',
       'democrat_candidate', 'republican_votes', 'democrat_votes',
       'county_totalvotes', 'winning candidate', 'winning party',
       'avg_wage_salary'],
      dtype='object')

In [63]:
eh_pop_df.head()

,ID,AGEGRP,FIPS,Year,STATE,COUNTY,STNAME,CTYNAME,SUMLEV,TOT_POP,...,fips,fips_trimmed,republican_candidate,democrat_candidate,republican_votes,democrat_votes,county_totalvotes,winning candidate,winning party,avg_wage_salary
0,201210001,Total,10001,2012,10,1,Delaware,Kent County,50,162955,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,201210003,Total,10003,2012,10,3,Delaware,New Castle County,50,538750,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,201210005,Total,10005,2012,10,5,Delaware,Sussex County,50,197890,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20121001,Total,1001,2012,1,1,Alabama,Autauga County,50,54754,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20121003,Total,1003,2012,1,3,Alabama,Baldwin County,50,183111,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [65]:
# save a copy of df to csv
eh_pop_df.to_csv('pop_agegroup_vEH.csv')